import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { CoreStore } from '../src/core-store.mjs';

let number = 0;
function makeStore() { const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cf2-stage1-')); const store=new CoreStore(path.join(dir,'core.db')); return {dir,store,done:()=>{store.close();fs.rmSync(dir,{recursive:true,force:true});}}; }
function command(type,payload, actor='CLAUDIO_DIRECT', expected_state_version) { const i=++number; return {command_id:`CMD:${i}`,command_type:type,actor_id:'ACTOR:TEST',actor_role:'TEST',issued_at:'2026-08-29T10:00:00Z',idempotency_key:`key-${i}`,...(expected_state_version===undefined?{}:{expected_state_version}),payload}; }
function entity(id,name,aliases=[]) { return {id,type:'ENTITY',status:'CURRENT',created_at:'2026-08-29T10:00:00Z',updated_at:'2026-08-29T10:00:00Z',basis_ref:['test'],entity_kind:'TRACK',canonical_name:name,aliases}; }
function decision(id,subject,value,authority='CLAUDIO_DIRECT',supersedes) { return {id,type:'DECISION',status:'CURRENT',created_at:'2026-08-29T10:00:00Z',updated_at:'2026-08-29T10:00:00Z',basis_ref:['test'],subject_id:subject,decision_key:'PROJECT_STATUS',value,authority,effective_at:'2026-08-29T10:00:00Z',...(supersedes?{supersedes}:{}),source_ref:'test'}; }
function verification(id,subject,attribute,klass,extra={}) { return {id,type:'VERIFICATION',status:'CURRENT',created_at:'2026-08-29T10:00:00Z',updated_at:'2026-08-29T10:00:00Z',basis_ref:['test'],subject_id:subject,attribute,value:'YES',class:klass,verified_at:'2026-08-29T10:00:00Z',verified_by:'TEST',evidence_ref:'evidence:test',...extra}; }

test('T01 lower authority cannot supersede higher authority',()=>{const x=makeStore();try { const high=decision('DECISION:HIGH','ENTITY:X','ACTIVE'); assert.equal(x.store.submitCommand(command('RECORD_DECISION',{object:high})).accepted,true); const low=decision('DECISION:LOW','ENTITY:X','FROZEN','ROLE_DELEGATED','DECISION:HIGH'); assert.equal(x.store.submitCommand(command('RECORD_DECISION',{object:low})).reason_code,'AUTHORITY_DENIED'); assert.equal(x.store.getCurrent('ENTITY:X','PROJECT_STATUS').object.id,'DECISION:HIGH'); } finally{x.done();}});
test('T02 valid supersession retains history and a single current',()=>{const x=makeStore();try {x.store.submitCommand(command('RECORD_DECISION',{object:decision('DECISION:OLD','ENTITY:X','OLD','DGA_DELEGATED')})); x.store.submitCommand(command('RECORD_DECISION',{object:decision('DECISION:NEW','ENTITY:X','NEW','CLAUDIO_DIRECT','DECISION:OLD')})); assert.equal(x.store.getCurrent('ENTITY:X','PROJECT_STATUS').object.id,'DECISION:NEW'); assert.equal(x.store.resolveEntity('missing').status,'UNKNOWN'); }finally{x.done();}});
test('T03 absent current is UNKNOWN, not false',()=>{const x=makeStore();try {const r=x.store.getCurrent('ENTITY:NO','ANY'); assert.equal(r.status,'UNKNOWN'); assert.equal(r.value,undefined);}finally{x.done();}});
test('T04 fixed verification remains current',()=>{const x=makeStore();try{x.store.submitCommand(command('RECORD_VERIFICATION',{object:verification('VERIFICATION:FIX','SURFACE:X','AI','FIJO')}));assert.equal(x.store.getCurrent('SURFACE:X','AI','2099-01-01T00:00:00Z').status,'CURRENT');}finally{x.done();}});
test('T05 volatile verification expires without inversion',()=>{const x=makeStore();try{x.store.submitCommand(command('RECORD_VERIFICATION',{object:verification('VERIFICATION:VOL','SURFACE:X','VISIBILITY','VOLÁTIL',{valid_until:'2026-08-29T10:01:00Z'})}));const r=x.store.getCurrent('SURFACE:X','VISIBILITY','2026-08-29T10:02:00Z');assert.equal(r.status,'EXPIRED');assert.equal(r.value,undefined);}finally{x.done();}});
test('T06 conditional invalidation is local',()=>{const x=makeStore();try{x.store.submitCommand(command('RECORD_VERIFICATION',{object:verification('VERIFICATION:C1','SURFACE:X','A','CONDICIONAL',{invalidation_rule:'EDIT_A'})}));x.store.submitCommand(command('RECORD_VERIFICATION',{object:verification('VERIFICATION:C2','SURFACE:X','B','CONDICIONAL',{invalidation_rule:'EDIT_B'})}));assert.equal(x.store.submitCommand(command('INVALIDATE_VERIFICATION',{subject_id:'SURFACE:X',attribute:'A',invalidation_rule:'EDIT_A'})).accepted,true);assert.equal(x.store.getCurrent('SURFACE:X','A').status,'UNKNOWN');assert.equal(x.store.getCurrent('SURFACE:X','B').status,'CURRENT');}finally{x.done();}});
test('T07 unique alias resolves and homonym is ambiguous',()=>{const x=makeStore();try{x.store.submitCommand(command('UPSERT_ENTITY',{object:entity('ENTITY:ONE','Uno',['unique'])}));assert.equal(x.store.resolveEntity('unique').status,'UNIQUE');assert.equal(x.store.resolveEntity('UNÍQUE').status,'UNIQUE');x.store.submitCommand(command('UPSERT_ENTITY',{object:entity('ENTITY:TWO','Dos',['same'])}));x.store.submitCommand(command('UPSERT_ENTITY',{object:entity('ENTITY:THREE','Tres',['same'])}));assert.equal(x.store.resolveEntity('same').reason_code,'AMBIGUOUS_ALIAS');}finally{x.done();}});
test('T08 derived view can be deleted or corrupted without changing core',()=>{const x=makeStore();try{x.store.submitCommand(command('UPSERT_ENTITY',{object:entity('ENTITY:VIEW','View')}));const key='ENTITY:ENTITY:VIEW';x.store.regenerateEntityView('ENTITY:VIEW');x.store.corruptView(key);x.store.deleteView(key);assert.equal(x.store.resolveEntity('ENTITY:VIEW').entity.canonical_name,'View');assert.equal(x.store.regenerateEntityView('ENTITY:VIEW').entity.id,'ENTITY:VIEW');}finally{x.done();}});
test('T09 task DONE requires an existing closure proof',()=>{const x=makeStore();try{const task={id:'TASK:X',type:'TASK',status:'OPEN',created_at:'2026-08-29T10:00:00Z',updated_at:'2026-08-29T10:00:00Z',basis_ref:['test'],action:'X',state:'OPEN',responsible_role:'TEST',related_ids:[]};x.store.submitCommand(command('CREATE_TASK',{object:task}));assert.equal(x.store.submitCommand(command('TRANSITION_TASK',{task_id:'TASK:X',state:'DONE',closure_ref:'proof:none'})).reason_code,'MISSING_CLOSURE_PROOF');x.store.registerDevProof('proof:closed');assert.equal(x.store.submitCommand(command('TRANSITION_TASK',{task_id:'TASK:X',state:'DONE',closure_ref:'proof:closed'})).accepted,true);}finally{x.done();}});
test('all six core types are persistible through the repository boundary',()=>{const x=makeStore();try{const base={created_at:'2026-08-29T10:00:00Z',updated_at:'2026-08-29T10:00:00Z',basis_ref:['test'],status:'CURRENT'};const surface={...base,id:'SURFACE:X',type:'SURFACE',platform:'YOUTUBE',surface_kind:'VIDEO',external_id:'exact-x',owner_or_subject_id:'ENTITY:X'};const relation={...base,id:'RELATION:X',type:'RELATION',from_id:'ENTITY:X',relation_type:'BELONGS_TO',to_id:'ENTITY:Y',effective_at:'2026-08-29T10:00:00Z'};assert.equal(x.store.submitCommand(command('REGISTER_SURFACE',{object:surface})).accepted,true);assert.equal(x.store.submitCommand(command('SET_RELATION',{object:relation})).accepted,true);assert.equal(x.store.getObject('SURFACE:X').external_id,'exact-x');assert.equal(x.store.getObject('RELATION:X').relation_type,'BELONGS_TO');}finally{x.done();}});
test('idempotency, audit and outbox share a committed mutation',()=>{const x=makeStore();try{const c=command('UPSERT_ENTITY',{object:entity('ENTITY:IDEMP','Idempotent')});const a=x.store.submitCommand(c);const b=x.store.submitCommand(c);assert.deepEqual(a,b);assert.equal(x.store.getAudit().length,1);const event=JSON.parse(x.store.getOutbox()[0].payload);assert.equal(x.store.getOutbox().length,1);assert.equal(event.event_type,'ACCEPTED');assert.equal(event.causation_id,c.command_id);assert.equal(event.state_version,a.resulting_state_version);}finally{x.done();}});
test('expected version conflict is local and leaves state intact',()=>{const x=makeStore();try{x.store.submitCommand(command('UPSERT_ENTITY',{object:entity('ENTITY:VERSION','Version')}));const r=x.store.submitCommand(command('UPSERT_ENTITY',{object:entity('ENTITY:OTHER','Other')},'CLAUDIO_DIRECT',0));assert.equal(r.reason_code,'VERSION_CONFLICT');assert.equal(x.store.resolveEntity('ENTITY:VERSION').status,'EXACT');}finally{x.done();}});
test('backup and restore preserve state and audit',()=>{const x=makeStore();try{x.store.submitCommand(command('UPSERT_ENTITY',{object:entity('ENTITY:BACKUP','Backup')}));const backup=x.store.backupTo(path.join(x.dir,'backup.db'));assert.ok(backup.bytes>0);const before=x.store.getAudit().length;x.store.restoreFrom(backup.backupPath);assert.equal(x.store.resolveEntity('ENTITY:BACKUP').entity.canonical_name,'Backup');assert.equal(x.store.getAudit().length,before);}finally{x.done();}});
