import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { CoreStore } from '../src/core-store.mjs';
import { CutoverError, CutoverJournal, PRODUCTION_CUTOVER_DISABLED, SingleWriterBarrier, WRITERS, applyDelta, calculateDelta, createCutoverDecision, logicalEquality, restoreR2Store, runStagingDrill } from '../src/cutover-tooling.mjs';

const at = () => '2026-08-30T18:00:00.000Z';
const decision = (scope = ['TASK']) => createCutoverDecision({ decision_id: 'CUTOVER_DECISION:TEST', scope, effective_at: at(), baseline_id: 'BASE', release_id: 'REL', approved_by: 'CLAUDIO_PALAIS_SIMULATION', previous_writer: 'CF1_WRITER', new_writer: 'CF2_WRITER', equality_check_ref: 'EQUAL:TEST', rollback_plan_ref: 'R0-R2', status: 'APPROVED_NOT_EXECUTED_SIMULATION', environment: 'STAGING' });

test('single writer barrier prevents two authoritative writers for one domain', () => { const barrier = new SingleWriterBarrier({ journal: new CutoverJournal({ at }) }); barrier.register(['TASK']); barrier.lock('TASK'); barrier.handoffToCF2('TASK', decision()); assert.equal(barrier.writer('TASK'), WRITERS.CF2); assert.throws(() => barrier.assertCanWrite('TASK', WRITERS.CF1), error => error.reason_code === 'FAIL_CLOSED'); });
test('missing Claudio simulation authority and production decision fail closed', () => { assert.throws(() => createCutoverDecision({}), error => error.reason_code === 'MISSING_EVIDENCE'); assert.throws(() => new SingleWriterBarrier({ environment: 'PRODUCTION' }), error => error.reason_code === 'PRODUCTION_CUTOVER_DISABLED'); assert.equal(PRODUCTION_CUTOVER_DISABLED, true); });
test('blocking and equal logical comparisons are explicit', () => { assert.equal(logicalEquality({ objects: [{ id: 'TASK:X', type: 'TASK', state: 'OPEN' }] }, { objects: [{ id: 'TASK:X', type: 'TASK', state: 'DONE' }] }, ['TASK']).result, 'BLOCKING_DIFF'); assert.equal(logicalEquality({ objects: [{ id: 'TASK:X', type: 'TASK', state: 'OPEN' }] }, { objects: [{ id: 'TASK:X', type: 'TASK', state: 'OPEN' }] }, ['TASK']).result, 'EQUAL'); });
test('final delta detects additions and task closure then applies only to shadow', () => { const before = { objects: [{ id: 'TASK:X', type: 'TASK', state: 'OPEN' }] }; const current = { objects: [{ id: 'TASK:X', type: 'TASK', state: 'DONE' }, { id: 'DECISION:Y', type: 'DECISION', status: 'CURRENT' }] }; const delta = calculateDelta(before, current); assert.equal(delta.counts.TASK_CLOSED, 1); assert.equal(delta.counts.NEW, 1); assert.equal(logicalEquality(current, applyDelta(before, delta), ['TASK', 'DECISION']).result, 'EQUAL'); });
test('R0 cancels locked writer without reconciliation', () => { const b = new SingleWriterBarrier({ journal: new CutoverJournal({ at }) }); b.register(['TASK']); b.lock('TASK'); b.rollbackR0('TASK'); assert.equal(b.writer('TASK'), WRITERS.CF1); });
test('R1 restores CF1 after early handoff and preserves reconciliation journal', () => { const journal = new CutoverJournal({ at }); const b = new SingleWriterBarrier({ journal }); b.register(['TASK']); b.lock('TASK'); b.handoffToCF2('TASK', decision()); b.rollbackR1('TASK', ['MUTATION:1']); assert.equal(b.writer('TASK'), WRITERS.CF1); assert.equal(journal.export().at(-1).event, 'ROLLBACK_R1'); });
test('R2 requires evidence and returns writer to CF1', () => { const b = new SingleWriterBarrier({ journal: new CutoverJournal({ at }) }); b.register(['RELATION']); b.lock('RELATION'); b.handoffToCF2('RELATION', decision(['RELATION'])); assert.throws(() => b.rollbackR2('RELATION', {}), error => error.reason_code === 'MISSING_EVIDENCE'); b.rollbackR2('RELATION', { backup_ref: 'B', audit_ref: 'A', outbox_ref: 'O', restored_digest: 'D' }); assert.equal(b.writer('RELATION'), WRITERS.CF1); });
test('R2 restores an isolated store backup and verifies its audit-inclusive digest', () => { const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'cf2-r2-')); const store = new CoreStore(path.join(dir, 'core.db')); try { const object = { id: 'ENTITY:R2', type: 'ENTITY', status: 'CURRENT', created_at: at(), updated_at: at(), basis_ref: ['test'], entity_kind: 'TRACK', canonical_name: 'R2', aliases: [] }; store.submitCommand({ command_id: 'CMD:R2:1', command_type: 'UPSERT_ENTITY', actor_id: 'TEST', actor_role: 'TEST', issued_at: at(), idempotency_key: 'r2-1', payload: { object } }); const digest = store.authoritativeDigest(); const backup = store.backupTo(path.join(dir, 'backup.db')); store.submitCommand({ command_id: 'CMD:R2:2', command_type: 'UPSERT_ENTITY', actor_id: 'TEST', actor_role: 'TEST', issued_at: at(), idempotency_key: 'r2-2', payload: { object: { ...object, id: 'ENTITY:R2:EXTRA', canonical_name: 'Extra' } } }); const evidence = restoreR2Store({ store, backup_path: backup.backupPath, expected_digest: digest, audit_ref: 'AUDIT:R2', outbox_ref: 'OUTBOX:R2' }); assert.equal(evidence.restored_digest, digest); assert.equal(store.getObject('ENTITY:R2:EXTRA'), null); } finally { store.close(); fs.rmSync(dir, { recursive: true, force: true }); } });
test('scope isolation leaves unrelated domain owned by CF1', () => { const b = new SingleWriterBarrier({ journal: new CutoverJournal({ at }) }); b.register(['TASK', 'DECISION']); b.lock('TASK'); b.handoffToCF2('TASK', decision()); assert.equal(b.writer('DECISION'), WRITERS.CF1); });
test('full staging drill journals all rollbacks and has zero production effects', () => { const drill = runStagingDrill({ at }); assert.equal(drill.equality.result, 'EQUAL'); assert.deepEqual(Object.values(drill.writers), [WRITERS.CF1, WRITERS.CF1, WRITERS.CF1]); assert.ok(drill.journal.some(entry => entry.event === 'ROLLBACK_R0')); assert.ok(drill.journal.some(entry => entry.event === 'ROLLBACK_R1')); assert.ok(drill.journal.some(entry => entry.event === 'ROLLBACK_R2')); assert.equal(drill.zero_production_side_effect, true); });
test('journal records an immutable trace', () => { const journal = new CutoverJournal({ at }); const entry = journal.append('TEST', { domain: 'TASK' }); assert.throws(() => { entry.event = 'MUTATED'; }, TypeError); assert.equal(journal.export().length, 1); });
