import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import {GitHubOidcAuthenticator,GITHUB_OIDC_ISSUER,CUTOVER_AUDIENCE,CUTOVER_PRINCIPAL} from '../src/github-oidc.mjs';
import {ProductionRoleInterface,CUTOVER_AUTHORITY_REF,MINIMUM_SCOPE} from '../src/production-role-interface.mjs';

const {publicKey,privateKey}=crypto.generateKeyPairSync('rsa',{modulusLength:2048});const jwk=publicKey.export({format:'jwk'});jwk.kid='test-key';jwk.alg='RS256';jwk.use='sig';
const base={iss:GITHUB_OIDC_ISSUER,aud:CUTOVER_AUDIENCE,iat:1000,exp:1100,repository:'palaisclaudio100/Sistema-CF2',repository_id:'1351688098',workflow_ref:'palaisclaudio100/Sistema-CF2/.github/workflows/cf2-minimum-cutover.yml@refs/heads/master',ref:'refs/heads/master',run_id:'1'};
const token=(overrides={})=>{const header=Buffer.from(JSON.stringify({alg:'RS256',kid:'test-key'})).toString('base64url'),payload=Buffer.from(JSON.stringify({...base,...overrides})).toString('base64url'),signature=crypto.sign('RSA-SHA256',Buffer.from(`${header}.${payload}`),privateKey).toString('base64url');return`${header}.${payload}.${signature}`;};
const auth=()=>new GitHubOidcAuthenticator({repository:base.repository,repositoryId:base.repository_id,workflowRef:base.workflow_ref,ref:base.ref,now:()=>1001,fetchImpl:async url=>({json:async()=>url.endsWith('openid-configuration')?{issuer:GITHUB_OIDC_ISSUER,jwks_uri:`${GITHUB_OIDC_ISSUER}/.well-known/jwks`}:{keys:[jwk]}})});

test('valid GitHub OIDC binds only the automation executor server-side',async()=>{const principal=await auth().authenticate(token());assert.equal(principal.actor_id,CUTOVER_PRINCIPAL.actor_id);assert.equal(principal.actor_role,'AUTOMATION_EXECUTOR');});
for(const [name,claim,value] of [['expired','exp',1000],['issuer','iss','https://evil.invalid'],['audience','aud','other'],['repository','repository','other/repo'],['repository id','repository_id','1'],['workflow','workflow_ref','other'],['ref','ref','refs/heads/other']])test(`rejects ${name} mismatch`,async()=>assert.rejects(auth().authenticate(token({[claim]:value})),error=>error.reason_code==='AUTH_REJECTED'));

test('production interface rejects identity declaration, absent/wrong authority and CF1 writer',async()=>{const calls=[],store={writer:async()=> 'CF1_WRITER',submitCommand:async command=>(calls.push(command),{accepted:true}),commandStatus:async()=>({}),getObject:async()=>null},roles=new ProductionRoleInterface(store,{productionEnabled:true,roleEnabled:true}),command={command_id:'C',command_type:'CREATE_TASK',idempotency_key:'I',payload:{object:{type:'TASK'}}};assert.equal((await roles.submit({principal:CUTOVER_PRINCIPAL,authority_ref:CUTOVER_AUTHORITY_REF,scope:MINIMUM_SCOPE,command:{...command,actor_id:'ACTOR:DGA'}})).reason_code,'ACTOR_MISMATCH');assert.equal((await roles.submit({principal:CUTOVER_PRINCIPAL,scope:MINIMUM_SCOPE,command})).reason_code,'AUTHORITY_REQUIRED');assert.equal((await roles.submit({principal:CUTOVER_PRINCIPAL,authority_ref:CUTOVER_AUTHORITY_REF,scope:['DECISION'],command})).reason_code,'AUTHORITY_REQUIRED');assert.equal((await roles.submit({principal:CUTOVER_PRINCIPAL,authority_ref:CUTOVER_AUTHORITY_REF,scope:MINIMUM_SCOPE,command})).reason_code,'WRITER_NOT_AUTHORIZED');assert.equal(calls.length,0);});

test('only CF2 writer permits a server-bound executor mutation',async()=>{const calls=[],store={writer:async()=> 'CF2_WRITER',submitCommand:async command=>(calls.push(command),{accepted:true}),commandStatus:async()=>({}),getObject:async()=>null},roles=new ProductionRoleInterface(store,{productionEnabled:true,roleEnabled:true}),result=await roles.submit({principal:CUTOVER_PRINCIPAL,authority_ref:CUTOVER_AUTHORITY_REF,scope:MINIMUM_SCOPE,command:{command_id:'C',command_type:'CREATE_TASK',idempotency_key:'I',payload:{object:{type:'TASK'}}}});assert.equal(result.accepted,true);assert.equal(calls[0].actor_id,CUTOVER_PRINCIPAL.actor_id);assert.equal(calls[0].actor_role,CUTOVER_PRINCIPAL.actor_role);});

test('production equality canonicalizes expected TASK order by exact ID',()=>{const source=fs.readFileSync(new URL('../src/production-cutover.mjs',import.meta.url),'utf8');assert.match(source,/expected=\[\.\.\.input\.objects\]\.sort\(\(a,b\)=>a\.id\.localeCompare\(b\.id\)\)/);assert.match(source,/ORDER BY id/);});

test('workflow is exact-ID, OIDC-only and keeps adapters off',()=>{const workflow=fs.readFileSync(new URL('../.github/workflows/cf2-minimum-cutover.yml',import.meta.url),'utf8'),server=fs.readFileSync(new URL('../src/prod-service.mjs',import.meta.url),'utf8');assert.match(workflow,/id-token: write/);assert.match(workflow,/srv-daa8dngae00c73a3m15g/);assert.match(workflow,/dpg-daa8fc67bikc73fn9c60-a/);assert.match(workflow,/db_host!=postgres_id/);assert.doesNotMatch(workflow,/GET','\/postgres\?limit/);assert.match(workflow,/details\.get\('plan',service\.get\('plan'\)\)/);assert.match(workflow,/plan!='0\.5c-512mb'/);assert.match(workflow,/\{'autoDeploy':'no'\}/);assert.match(workflow,/SERVICE_AUTODEPLOY_DISABLE_FAILED/);assert.match(workflow,/h\['release_id'\]==os\.environ\['TARGET_COMMIT'\]/);assert.match(workflow,/consecutive" -ge 6/g);assert.match(workflow,/production_cutover_enabled':True/);assert.match(workflow,/cf2-prod-role-interface/);assert.match(workflow,/CF2_EXTERNAL_ADAPTERS_ENABLED':'false'/);assert.doesNotMatch(workflow,/ACTOR:DGA/);assert.match(server,/enabled\(process\.env\.CF2_PRODUCTION_WRITER_ENABLED\)/);assert.match(server,/external_adapters_enabled:false/);});
