import test from 'node:test';
import assert from 'node:assert/strict';
import {ActorTransport,ACTORS,sha} from '../src/actor-transport.mjs';
import {CanonGateway,parseControl,CONTROL_ID,CANON_OBJECTS} from '../src/canon-gateway.mjs';
import {OrchestrationApi} from '../src/orchestration-api.mjs';
class Memory{
  rows=new Map();
  async create(t){if(this.rows.has(t.thread_id))throw new Error('THREAD_ALREADY_EXISTS');this.rows.set(t.thread_id,structuredClone(t));return structuredClone(t);}
  async read(id){return structuredClone(this.rows.get(id));}
  async change(id,fn){const next=await fn(await this.read(id));this.rows.set(id,structuredClone(next));return structuredClone(next);}
  async list(actor){return [...this.rows.values()].filter(t=>t.participants.includes(actor)).map(t=>structuredClone(t));}
  async byTask(task_id){return [...this.rows.values()].filter(t=>t.task_id===task_id).map(t=>structuredClone(t));}
  async active(){return [...this.rows.values()].filter(t=>!['CLOSED','CANCELLED'].includes(t.state)).map(t=>structuredClone(t));}
  async pending(actor){return(await this.list(actor)).filter(t=>!['CLOSED','CANCELLED'].includes(t.state));}
}
const principal=actor_id=>({actor_id});const [D,G,C,X,A]=ACTORS.map(principal);
const setup=()=>{let time=Date.parse('2026-09-05T00:00:00Z');const repo=new Memory(),bus=new ActorTransport(repo,{clock:()=>time,leaseMs:1000});return{bus,repo,advance:()=>time+=1001};};
const start=(bus,stages=[G.actor_id,C.actor_id,X.actor_id])=>bus.start(D,{thread_id:'THREAD:CANARY:ORCHESTRATION:test',stages,payload:{operation:'CANON_CLOSURE_REVIEW',external_effects:0}});
const finish=async(bus,p,request,payload={result:'PASS'})=>bus.reply(p,{thread_id:request.thread_id,message_id:request.message_id,type:'RESPONSE',payload,lease_token:request.lease_token},{leaseRequired:true});
test('full return path persists each authenticated actor and leaves no requests pending',async()=>{const {bus}=setup();await start(bus);for(const p of [G,C,X]){const request=await bus.claim(p);assert.equal(request.recipient,p.actor_id);const result=await finish(bus,p,request);assert.equal(result.messages.find(m=>m.reply_to===request.message_id).recipient,D.actor_id);}let t=await bus.read(D,'THREAD:CANARY:ORCHESTRATION:test');assert.equal(t.state,'READY_TO_CLOSE');assert.deepEqual(t.messages.filter(m=>m.type==='RESPONSE').map(m=>m.sender),[G.actor_id,C.actor_id,X.actor_id]);t=await bus.control(D,{thread_id:t.thread_id,operation:'CLOSE'});assert.equal(t.state,'CLOSED');assert.equal(t.messages.filter(m=>['PENDING','RUNNING'].includes(m.state)).length,0);assert.equal(t.audit.filter(a=>a.event==='AUTOMATIC_RETURN').length,3);assert.deepEqual(Object.values(t.metrics),[0,0,0,0]);});
test('no sender spoofing through any start argument',async()=>{const {bus}=setup();await assert.rejects(bus.start(D,{thread_id:'t',stages:[G.actor_id],payload:{},actor_id:G.actor_id}),/INVALID_SCHEMA/);});
test('unrelated actors cannot read threads or reply',async()=>{const {bus}=setup();const t=await start(bus,[G.actor_id]);await assert.rejects(bus.read(C,t.thread_id),/ROLE_FORBIDDEN/);await assert.rejects(bus.reply(C,{thread_id:t.thread_id,message_id:t.messages[0].message_id,type:'RESPONSE',payload:{}}),/ROLE_FORBIDDEN/);});
test('Diego orchestration does not permit other actors to activate Claude Code',async()=>{const {bus}=setup();await assert.rejects(bus.start(G,{thread_id:'t',stages:[A.actor_id],payload:{}}),/ROLE_FORBIDDEN/);const t=await start(bus,[A.actor_id]);assert.equal((await bus.claim(A)).thread_id,t.thread_id);});
test('multi actor workflow requires Diego',async()=>{const {bus}=setup();await assert.rejects(bus.start(G,{thread_id:'t',stages:[C.actor_id,X.actor_id],payload:{}}),/ROLE_FORBIDDEN/);});
test('lease fences stale and duplicate execution, completion is idempotent',async()=>{const {bus,advance}=setup();await start(bus,[G.actor_id]);const first=await bus.claim(G);assert.equal(await bus.claim(G),null);advance();const second=await bus.claim(G);assert.notEqual(first.lease_token,second.lease_token);await assert.rejects(finish(bus,G,first),/LEASE_REJECTED/);await finish(bus,G,second);const again=await finish(bus,G,second);assert.equal(again.messages.filter(m=>m.type==='RESPONSE').length,1);await assert.rejects(finish(bus,G,second,{different:true}),/IDEMPOTENCY_CONFLICT/);});
test('objection suspends routing until Diego resolves it',async()=>{const {bus}=setup();const t=await start(bus);const request=await bus.claim(G);await bus.reply(G,{thread_id:t.thread_id,message_id:request.message_id,type:'OBJECTION',payload:{reason:'MISSING_EVIDENCE'},lease_token:request.lease_token},{leaseRequired:true});assert.equal(await bus.claim(C),null);await assert.rejects(bus.control(G,{thread_id:t.thread_id,operation:'RESOLVE_OBJECTION',payload:{resolution:'retry'}}),/ROLE_FORBIDDEN/);await bus.control(D,{thread_id:t.thread_id,operation:'RESOLVE_OBJECTION',payload:{resolution:'retry'}});assert.ok(await bus.claim(G));});
test('cancellation fences in-flight completions and preserves audit',async()=>{const {bus}=setup();const t=await start(bus);const r=await bus.claim(G);await bus.control(D,{thread_id:t.thread_id,operation:'CANCEL'});await assert.rejects(finish(bus,G,r),/THREAD_TERMINAL/);assert.equal((await bus.read(D,t.thread_id)).state,'CANCELLED');});
test('technical routing is not a Claudio decision',async()=>{const {bus}=setup();const t=await start(bus);await assert.rejects(bus.control(D,{thread_id:t.thread_id,operation:'CLAUDIO_DECISION_REQUIRED',reason:'FILE_TRANSPORT',payload:{}}),/INVALID_DECISION_REASON/);const out=await bus.control(D,{thread_id:t.thread_id,operation:'CLAUDIO_DECISION_REQUIRED',reason:'RELEASE_CATALOG',payload:{question:'Authority required'}});assert.equal(out.metrics.CLAUDIO_DECISION_ESCALATIONS,1);assert.equal(await bus.claim(G),null);});
test('Courier MVP transports Diego to Chat to CW to Diego with envelopes, acknowledgements and no Claudio route',async()=>{const {bus}=setup();const t=await start(bus,[G.actor_id]);const chatRequest=await bus.claim(G);assert.equal(chatRequest.message_type,'TASK_REQUEST');assert.equal(chatRequest.envelope_state,'QUEUED');const first=await bus.send(G,{thread_id:t.thread_id,recipient:C.actor_id,type:'TASK_REQUEST',payload:{canary:true,operation:'NON_PRODUCTIVE'},idempotency_key:'chat-cw-canary'});const replay=await bus.send(G,{thread_id:t.thread_id,recipient:C.actor_id,type:'TASK_REQUEST',payload:{canary:true,operation:'NON_PRODUCTIVE'},idempotency_key:'chat-cw-canary'});assert.equal(first.messages.length,replay.messages.length);const cwRequest=await bus.claim(C);const acknowledged=await bus.reply(C,{thread_id:t.thread_id,message_id:cwRequest.message_id,type:'ACK',payload:{received:true}});assert.equal(acknowledged.messages.find(m=>m.message_id===cwRequest.message_id).envelope_state,'ACKNOWLEDGED');const cwResult=await bus.reply(C,{thread_id:t.thread_id,message_id:cwRequest.message_id,type:'RESULT',payload:{result:'PASS',canary:true},lease_token:cwRequest.lease_token},{leaseRequired:true});assert.equal(cwResult.messages.at(-1).destination_actor,G.actor_id);const done=await bus.reply(G,{thread_id:t.thread_id,message_id:chatRequest.message_id,type:'RESULT',payload:{result:'PASS',derived_from:cwRequest.envelope_id},lease_token:chatRequest.lease_token},{leaseRequired:true});assert.equal(done.messages.find(m=>m.message_id===chatRequest.message_id).envelope_state,'RESPONDED');assert.equal(done.messages.filter(m=>m.origin_actor==='ACTOR:CLAUDIO').length,0);assert.equal(done.metrics.CLAUDIO_MANUAL_HANDOFFS,0);});
test('Diego and Codex complete two direct read-only Courier workflows with ACK, result and closure',async()=>{const {bus}=setup();for(const suffix of ['ONE','TWO']){const thread_id=`THREAD:CANARY:DIEGO_CODEX:${suffix}`;const started=await bus.start(D,{thread_id,stages:[X.actor_id],payload:{operation:'READ_ONLY_CANARY',external_effects:0}});const request=await bus.claim(X);assert.equal(request.envelope_state,'QUEUED');const acked=await bus.reply(X,{thread_id,message_id:request.message_id,type:'ACK',payload:{received:true,runtime:'codex-role-runtime'},lease_token:request.lease_token},{leaseRequired:true});assert.equal(acked.messages.find(m=>m.message_id===request.message_id).state,'RUNNING');assert.equal(acked.messages.find(m=>m.message_id===request.message_id).envelope_state,'ACKNOWLEDGED');const completed=await bus.reply(X,{thread_id,message_id:request.message_id,type:'RESULT',payload:{result:'PASS',canary:'READ_ONLY_CANARY',external_effects:0},lease_token:request.lease_token},{leaseRequired:true});const result=completed.messages.find(m=>m.reply_to===request.message_id&&m.message_type==='RESULT');assert.equal(result.destination_actor,D.actor_id);assert.equal(result.correlation_id,started.correlation_id);assert.equal(completed.metrics.CLAUDIO_MANUAL_HANDOFFS,0);const closed=await bus.control(D,{thread_id,operation:'CLOSE'});assert.equal(closed.state,'CLOSED');assert.equal(closed.messages.some(m=>m.origin_actor==='ACTOR:CLAUDIO'),false);}});
test('retry exhaustion preserves a Courier dead letter and returns an ERROR envelope',async()=>{const {repo}=setup();let time=0;const bus=new ActorTransport(repo,{clock:()=>time,leaseMs:1,maxAttempts:1});const t=await bus.start(D,{thread_id:'THREAD:CANARY:DEAD_LETTER',stages:[G.actor_id],payload:{canary:true}});await bus.claim(G);time=2;await bus.claim(G);const result=await bus.read(D,t.thread_id);assert.equal(result.dead_letters.length,1);assert.equal(result.dead_letters[0].origin_actor,D.actor_id);assert.equal(result.messages.find(m=>m.envelope_id===result.dead_letters[0].envelope_id).envelope_state,'FAILED');assert.equal(result.messages.at(-1).message_type,'ERROR');});
test('send replay rejects different content and a forbidden Courier route',async()=>{const {bus}=setup();const t=await start(bus,[G.actor_id]);const args={thread_id:t.thread_id,recipient:D.actor_id,type:'EVIDENCE',payload:{proof:1},idempotency_key:'k'};await bus.send(G,args);await bus.send(G,args);await assert.rejects(bus.send(G,{...args,payload:{proof:2}}),/IDEMPOTENCY_CONFLICT/);await assert.rejects(bus.send(G,{...args,idempotency_key:'k2',recipient:A.actor_id}),/ROLE_FORBIDDEN/);});
const bodies={MAESTRO:Buffer.from('# Roles\nGaby Chat defines operational requirements.\n# Other\nValue'),ESTADO:Buffer.from('# Session\nCurrent status')};
const control=()=>`ID NUEVO DE CORRIDA: CODEX-CANON-ESPEJO-MANUAL-ASISTIDO-20260904-230109-IDT\nOBJETO BASE: CANON LOCAL.\n${Object.entries(CANON_OBJECTS).map(([k,v])=>`${k} — ID ${v.id}; ${bodies[k].length} B; SHA-256 ${sha(bodies[k])}.`).join('\n')}\nCONTROL: VIGENTE.\nCONTROL_PERSISTIDO_VERIFICADO.\nSINCRONIZADO_VERIFICADO.\nCORRIDA ANTERIOR HISTÓRICA\nUNVERIFIED`;
const source=()=>({control:async()=>({id:CONTROL_ID,version:'r1',text:control()}),bytes:async name=>bodies[name]});
test('canon search and bounded sections return Control identity and SHA evidence',async()=>{const gateway=new CanonGateway(source());const r=await gateway.call(G,'canon_search',{object:'MAESTRO',query:'Gaby'});assert.equal(r.matches[0].line,2);assert.equal(r.metadata.sha256,sha(bodies.MAESTRO));assert.equal(r.metadata.sync_state,'SINCRONIZADO_VERIFICADO');const section=await gateway.call(G,'canon_read',{object:'MAESTRO',section:'Roles'});assert.equal(section.lines.length,2);assert.equal((await gateway.call(G,'canon_identify',{})).objects.length,2);});
test('bad or stale mirror never serves text and escalates to technical handler',async()=>{let incident;const s=source();s.bytes=async()=>Buffer.from('different');const gateway=new CanonGateway(s,{onIncident:async(p,o)=>incident={p,o}});await assert.rejects(gateway.call(G,'canon_read',{object:'MAESTRO'}),/CANON_NOT_VERIFIED/);assert.equal(incident.p.actor_id,G.actor_id);assert.equal(incident.o,'MAESTRO');});
test('Control change during read fails closed',async()=>{let revision=0;const s=source();s.control=async()=>({id:CONTROL_ID,version:String(++revision),text:control()});await assert.rejects(new CanonGateway(s).call(G,'canon_identify',{}),/CANON_NOT_VERIFIED/);});
test('historical green cannot override a failed current Control',()=>{assert.throws(()=>parseControl('CURRENT FAILED\nCORRIDA ANTERIOR HISTÓRICA\n'+control()),/CANON_NOT_VERIFIED/);});
test('worker claim accepts only an empty object',async()=>{const {bus}=setup();const api=new OrchestrationApi(bus,new CanonGateway(source()),{workerKeys:{[sha('secret')]:{actor_id:G.actor_id,expires_at:'2099-01-01T00:00:00Z'}}});const p=await api.authenticateWorker({headers:{authorization:'Bearer secret'}});assert.equal(await api.worker(p,'claim',{}),null);for(const args of [null,[],{foo:'bar'},{limit:1},{actor_id:X.actor_id}])await assert.rejects(api.worker(p,'claim',args),/INVALID_SCHEMA/);});
test('worker identity comes only from token registry, expiry enforced and cannot dispatch',async()=>{const {bus}=setup();const api=new OrchestrationApi(bus,new CanonGateway(source()),{workerKeys:{[sha('secret')]:{actor_id:G.actor_id,expires_at:'2099-01-01T00:00:00Z'},[sha('old')]:{actor_id:X.actor_id,expires_at:'2000-01-01T00:00:00Z'}}});const p=await api.authenticateWorker({headers:{authorization:'Bearer secret'}});assert.equal(p.actor_id,G.actor_id);assert.equal(await api.authenticateWorker({headers:{authorization:'Bearer old'}}),null);await assert.rejects(api.worker(p,'start_workflow',{}),/ROLE_FORBIDDEN/);await assert.rejects(api.worker(p,'claim',{actor_id:C.actor_id}),/INVALID_SCHEMA/);});
test('execution projection is discoverable from task and protects the active lease',async()=>{const {bus}=setup();const thread=await bus.start(D,{thread_id:'THREAD:EXECUTION:ONE',stages:[X.actor_id],task_id:'TASK:EXECUTION:ONE',payload:{operation:'READ_ONLY_CANARY',external_effects:0}});const job=await bus.claim(X);await bus.reply(X,{thread_id:thread.thread_id,message_id:job.message_id,type:'ACK',payload:{received:true},lease_token:job.lease_token},{leaseRequired:true});await bus.executionEvent(X,{thread_id:thread.thread_id,message_id:job.message_id,lease_token:job.lease_token,kind:'PROGRESS',summary:'BOT_CODEX_IMPLEMENTATION'});const execution=await bus.executionForTask(D,'TASK:EXECUTION:ONE');assert.equal(execution.thread_id,thread.thread_id);assert.equal(execution.state,'RUNNING');assert.equal(execution.progress_seq,1);assert.equal(execution.last_progress_summary,'BOT_CODEX_IMPLEMENTATION');await assert.rejects(bus.executionEvent(G,{thread_id:thread.thread_id,message_id:job.message_id,lease_token:job.lease_token,kind:'HEARTBEAT',summary:'spoof'}),/ROLE_FORBIDDEN/);});
test('multiple active executions fail closed and a stall is persisted then cleared',async()=>{let time=0;const repo=new Memory(),bus=new ActorTransport(repo,{clock:()=>time,leaseMs:200000});const t=await bus.start(D,{thread_id:'THREAD:EXECUTION:STALL',stages:[X.actor_id],task_id:'TASK:EXECUTION:STALL',payload:{operation:'READ_ONLY_CANARY',external_effects:0}});const job=await bus.claim(X);for(const suffix of ['A','B'])await bus.start(D,{thread_id:`THREAD:EXECUTION:${suffix}`,stages:[X.actor_id],task_id:'TASK:EXECUTION:DUPLICATE',payload:{operation:'READ_ONLY_CANARY',external_effects:0}});const ambiguous=await bus.executionForTask(D,'TASK:EXECUTION:DUPLICATE');assert.equal(ambiguous.state,'MULTIPLE_ACTIVE_EXECUTIONS');time=181000;await bus.supervise({runtimeLastSeen:{[X.actor_id]:time}});let observed=await bus.read(D,t.thread_id);assert.equal(observed.execution.state,'STALLED');assert.equal(observed.execution.reason_code,'RUNNING_NO_HEARTBEAT');assert.equal(observed.audit.at(-1).event,'STALL_DETECTED');await bus.executionEvent(X,{thread_id:t.thread_id,message_id:job.message_id,lease_token:job.lease_token,kind:'HEARTBEAT',summary:'RECOVERED'});await bus.supervise({runtimeLastSeen:{[X.actor_id]:time}});observed=await bus.read(D,t.thread_id);assert.equal(observed.execution.state,'ACKNOWLEDGED');assert.ok(observed.audit.some(event=>event.event==='STALL_CLEARED'));});
test('supervisor classifies every configured stall threshold without changing task ownership',async()=>{const make=async()=>{let time=0;const repo=new Memory(),bus=new ActorTransport(repo,{clock:()=>time,leaseMs:2000000});const t=await bus.start(D,{thread_id:'THREAD:EXECUTION:'+Math.random(),stages:[X.actor_id],task_id:'TASK:EXECUTION:'+Math.random(),payload:{operation:'READ_ONLY_CANARY',external_effects:0}});return{bus,t,now:value=>time=value,runtime:()=>({[X.actor_id]:time})};};const cases=[['ASSIGNED_NO_ACK',async f=>{f.now(120001);}],[ 'ACK_NO_START',async f=>{const j=await f.bus.claim(X);await f.bus.reply(X,{thread_id:f.t.thread_id,message_id:j.message_id,type:'ACK',payload:{received:true},lease_token:j.lease_token},{leaseRequired:true});f.now(120001);}],[ 'RUNNING_NO_HEARTBEAT',async f=>{await f.bus.claim(X);f.now(180001);}],[ 'HEARTBEAT_NO_PROGRESS',async f=>{const j=await f.bus.claim(X);await f.bus.executionEvent(X,{thread_id:f.t.thread_id,message_id:j.message_id,lease_token:j.lease_token,kind:'PROGRESS',summary:'STARTED'});f.now(800000);await f.bus.executionEvent(X,{thread_id:f.t.thread_id,message_id:j.message_id,lease_token:j.lease_token,kind:'HEARTBEAT',summary:'ALIVE'});f.now(900001);}],[ 'RESULT_NOT_RETURNED',async f=>{const j=await f.bus.claim(X);await f.bus.executionEvent(X,{thread_id:f.t.thread_id,message_id:j.message_id,lease_token:j.lease_token,kind:'FINISHED',summary:'FINISHED'});f.now(120001);}],[ 'ACTOR_RUNTIME_UNAVAILABLE',async f=>{f.now(15001);}]];for(const [reason,arrange] of cases){const f=await make();await arrange(f);await f.bus.supervise({runtimeLastSeen:reason==='ACTOR_RUNTIME_UNAVAILABLE'?{}:f.runtime()});const observed=await f.bus.read(D,f.t.thread_id);assert.equal(observed.execution.reason_code,reason);assert.equal(observed.task_id??f.t.task_id,f.t.task_id);assert.equal(observed.audit.at(-1).event,'STALL_DETECTED');}});
test('valid heartbeat clears runtime stall and terminal BLOCKED state takes precedence',async()=>{let time=0;const repo=new Memory(),bus=new ActorTransport(repo,{clock:()=>time,leaseMs:300000});const thread=await bus.start(D,{thread_id:'THREAD:EXECUTION:RECOVERY',stages:[X.actor_id],task_id:'TASK:EXECUTION:RECOVERY',payload:{operation:'READ_ONLY_CANARY',external_effects:0}}),job=await bus.claim(X);time=15001;await bus.supervise({runtimeLastSeen:{}});let current=await bus.executionForTask(D,'TASK:EXECUTION:RECOVERY');assert.equal(current.state,'STALLED');assert.equal(current.reason_code,'ACTOR_RUNTIME_UNAVAILABLE');await bus.executionEvent(X,{thread_id:thread.thread_id,message_id:job.message_id,lease_token:job.lease_token,kind:'HEARTBEAT',summary:'RUNTIME_RECOVERED'});await bus.executionEvent(X,{thread_id:thread.thread_id,message_id:job.message_id,lease_token:job.lease_token,kind:'BLOCKED',summary:'EXECUTOR_UNAVAILABLE'});await bus.executionEvent(X,{thread_id:thread.thread_id,message_id:job.message_id,lease_token:job.lease_token,kind:'FINISHED',summary:'EXECUTION_BLOCKED'});await bus.reply(X,{thread_id:thread.thread_id,message_id:job.message_id,lease_token:job.lease_token,type:'OBJECTION',payload:{result:'BLOCKED',error_code:'EXECUTOR_UNAVAILABLE'}},{leaseRequired:true});current=await bus.executionForTask(D,'TASK:EXECUTION:RECOVERY');assert.equal(current.state,'BLOCKED');assert.equal(current.reason_code,'EXECUTOR_UNAVAILABLE');assert.equal(current.last_stall_reason,'ACTOR_RUNTIME_UNAVAILABLE');const audit=(await bus.read(D,thread.thread_id)).audit.map(event=>event.event);assert.ok(audit.includes('STALL_DETECTED'));assert.ok(audit.includes('STALL_CLEARED'));assert.ok(audit.includes('EXECUTION_FINISHED'));assert.ok(audit.includes('AUTOMATIC_RETURN'));});
test('historical completed execution never promotes stall history into terminal reason',async()=>{const {bus,repo}=setup();const thread=await bus.start(D,{thread_id:'THREAD:EXECUTION:LEGACY',stages:[X.actor_id],task_id:'TASK:EXECUTION:LEGACY',payload:{operation:'READ_ONLY_CANARY',external_effects:0}}),job=await bus.claim(X);await bus.reply(X,{thread_id:thread.thread_id,message_id:job.message_id,lease_token:job.lease_token,type:'OBJECTION',payload:{result:'BLOCKED',error_code:'ACTOR_RUNTIME_UNAVAILABLE'}},{leaseRequired:true});await repo.change(thread.thread_id,t=>{const request=t.messages.find(m=>m.message_id===job.message_id);delete request.terminal_state;delete request.terminal_reason_code;delete request.response_type;request.stall_type='ACTOR_RUNTIME_UNAVAILABLE';request.reason_code='ACTOR_RUNTIME_UNAVAILABLE';return t;});const execution=await bus.executionForTask(D,'TASK:EXECUTION:LEGACY');assert.equal(execution.state,'BLOCKED');assert.equal(execution.terminal_reason_code,null);assert.equal(execution.reason_code,null);assert.equal(execution.last_stall_reason,'ACTOR_RUNTIME_UNAVAILABLE');});
test('task execution selection prefers one active, then latest terminal, and never invents one',async()=>{const {bus,advance}=setup(),task='TASK:EXECUTION:SELECTION';const terminal=async suffix=>{const t=await bus.start(D,{thread_id:`THREAD:EXECUTION:${suffix}`,stages:[X.actor_id],task_id:task,payload:{operation:'READ_ONLY_CANARY',external_effects:0}}),job=await bus.claim(X);await bus.reply(X,{thread_id:t.thread_id,message_id:job.message_id,lease_token:job.lease_token,type:'OBJECTION',payload:{result:'BLOCKED'}},{leaseRequired:true});return t;};const first=await terminal('FIRST');advance();const second=await terminal('SECOND');let execution=await bus.executionForTask(D,task);assert.equal(execution.thread_id,second.thread_id);const active=await bus.start(D,{thread_id:'THREAD:EXECUTION:ACTIVE',stages:[X.actor_id],task_id:task,payload:{operation:'READ_ONLY_CANARY',external_effects:0}});execution=await bus.executionForTask(D,task);assert.equal(execution.thread_id,active.thread_id);assert.equal(execution.state,'NOT_STARTED');assert.deepEqual(await bus.executionForTask(D,'TASK:EXECUTION:NONE'),{state:'NOT_STARTED',task_id:'TASK:EXECUTION:NONE'});assert.notEqual(first.thread_id,second.thread_id);});
