import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { CoreStore } from '../src/core-store.mjs';

let sequence=0; const stamp='2026-08-29T10:00:00Z';
const cmd=(command_type,payload)=>({command_id:`CMD:READ:${++sequence}`,command_type,actor_id:'ACTOR:TEST',actor_role:'TEST',issued_at:stamp,idempotency_key:`read-${sequence}`,payload});
const entity=(id,name,aliases=[],entity_kind='ARTIST')=>({id,type:'ENTITY',status:'CURRENT',created_at:stamp,updated_at:stamp,basis_ref:['test'],entity_kind,canonical_name:name,aliases});
const verification=(id,attribute,klass,extra={})=>({id,type:'VERIFICATION',status:'CURRENT',created_at:stamp,updated_at:stamp,basis_ref:['test'],subject_id:'SURFACE:YOUTUBE:SM',attribute,value:'YES',class:klass,verified_at:stamp,verified_by:'TEST',evidence_ref:'evidence:test',...extra});
function setup(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cf2-stage2-'));const store=new CoreStore(path.join(dir,'core.db'));const put=(type,object)=>assert.equal(store.submitCommand(cmd(type,{object})).accepted,true);put('UPSERT_ENTITY',entity('ENTITY:MITXODA','Mitxoda',['mitxoda artist']));put('UPSERT_ENTITY',entity('ENTITY:INDEPENDIZA','Independiza',['independiza music'],'PROVIDER'));put('UPSERT_ENTITY',entity('ENTITY:SOMOS_MAS','Somos más',['Somos mas'],'PROJECT'));put('UPSERT_ENTITY',entity('ENTITY:LM110','LM110',[],'TRACK'));put('REGISTER_SURFACE',{id:'SURFACE:YOUTUBE:SM',type:'SURFACE',status:'CURRENT',created_at:stamp,updated_at:stamp,basis_ref:['test'],platform:'YOUTUBE',surface_kind:'VIDEO',external_id:'exact-sm',owner_or_subject_id:'ENTITY:SOMOS_MAS'});put('SET_RELATION',{id:'RELATION:LM110:SOMOS',type:'RELATION',status:'CURRENT',created_at:stamp,updated_at:stamp,basis_ref:['test'],from_id:'ENTITY:LM110',relation_type:'BELONGS_TO',to_id:'ENTITY:SOMOS_MAS',effective_at:stamp});put('RECORD_DECISION',{id:'DECISION:SOMOS:OLD',type:'DECISION',status:'CURRENT',created_at:stamp,updated_at:stamp,basis_ref:['test'],subject_id:'ENTITY:SOMOS_MAS',decision_key:'PROJECT_STATUS',value:'FROZEN',authority:'DGA_DELEGATED',effective_at:stamp,source_ref:'test'});put('RECORD_DECISION',{id:'DECISION:SOMOS:CURRENT',type:'DECISION',status:'CURRENT',created_at:stamp,updated_at:stamp,basis_ref:['test'],subject_id:'ENTITY:SOMOS_MAS',decision_key:'PROJECT_STATUS',value:'ACTIVE_CONSTRUCTION',authority:'CLAUDIO_DIRECT',effective_at:stamp,supersedes:'DECISION:SOMOS:OLD',source_ref:'test'});put('RECORD_VERIFICATION',verification('VERIFICATION:FIXED','AI_USAGE','FIJO'));put('RECORD_VERIFICATION',verification('VERIFICATION:EXPIRED','VISIBILITY','VOLÁTIL',{valid_until:'2026-08-29T09:00:00Z'}));const task={id:'TASK:OPEN',type:'TASK',status:'OPEN',created_at:stamp,updated_at:stamp,basis_ref:['test'],action:'REVIEW',state:'OPEN',responsible_role:'DGA',related_ids:['ENTITY:SOMOS_MAS']};put('CREATE_TASK',task);return {store,done:()=>{store.close();fs.rmSync(dir,{recursive:true,force:true});}};}

test('alias, canonical, ID and exact surface resolution are fail-closed',()=>{const x=setup();try{assert.equal(x.store.resolveEntity('ENTITY:MITXODA').status,'EXACT');assert.equal(x.store.resolveEntity('MITXODA ARTIST').entity.id,'ENTITY:MITXODA');assert.equal(x.store.resolveEntity('Somos mas').entity.id,'ENTITY:SOMOS_MAS');assert.equal(x.store.resolveSurface({platform:'YOUTUBE',external_id:'exact-sm'}).surface.id,'SURFACE:YOUTUBE:SM');assert.equal(x.store.resolveEntity('No antecedente').reason_code,'ENTITY_CANDIDATE_NEW');}finally{x.done();}});
test('CURRENT excludes superseded and history returns it on demand',()=>{const x=setup();try{assert.equal(x.store.getCurrent('ENTITY:SOMOS_MAS','PROJECT_STATUS').object.id,'DECISION:SOMOS:CURRENT');const history=x.store.getHistory('ENTITY:SOMOS_MAS','PROJECT_STATUS');assert.deepEqual(history.decisions.map(d=>d.id),['DECISION:SOMOS:OLD','DECISION:SOMOS:CURRENT']);}finally{x.done();}});
test('snapshot is structured and contains no narrative corpus',()=>{const x=setup();try{const snapshot=x.store.getSnapshot();assert.equal(snapshot.kind,'STARTUP_SNAPSHOT');assert.equal(snapshot.current_decisions[0].id,'DECISION:SOMOS:CURRENT');assert.equal(snapshot.main_relations[0].from_id,'ENTITY:LM110');assert.equal(JSON.stringify(snapshot).includes('corpus'),false);}finally{x.done();}});
test('entity cards recover Mitxoda and Independiza from core only',()=>{const x=setup();try{assert.equal(x.store.getEntityCard('ENTITY:MITXODA').entity.canonical_name,'Mitxoda');assert.equal(x.store.getEntityCard('ENTITY:INDEPENDIZA').entity.entity_kind,'PROVIDER');}finally{x.done();}});
test('surface CURRENT view excludes expired; history exposes it on demand',()=>{const x=setup();try{const view=x.store.getSurfaceView('SURFACE:YOUTUBE:SM');assert.equal(view.verifications.find(v=>v.attribute==='AI_USAGE').validity,'CURRENT');assert.equal(view.verifications.some(v=>v.attribute==='VISIBILITY'),false);assert.equal(x.store.getHistory('SURFACE:YOUTUBE:SM','VISIBILITY').verifications[0].id,'VERIFICATION:EXPIRED');}finally{x.done();}});
test('task operational view excludes DONE and CANCELLED',()=>{const x=setup();try{const groups=x.store.getTaskView().groups;assert.equal(groups.OPEN[0].id,'TASK:OPEN');assert.deepEqual(Object.keys(groups),['OPEN','READY','IN_PROGRESS','BLOCKED']);}finally{x.done();}});
test('delete and regenerate all views leaves authoritative digest identical',()=>{const x=setup();try{const before=x.store.authoritativeDigest();const generated=x.store.regenerateAllViews();assert.equal(generated.entities,4);assert.equal(x.store.deleteAllViews()>0,true);assert.equal(x.store.authoritativeDigest(),before);x.store.regenerateAllViews();assert.equal(x.store.authoritativeDigest(),before);}finally{x.done();}});
test('corrupted derived view is invalid and cannot change CURRENT',()=>{const x=setup();try{x.store.regenerateEntityView('ENTITY:INDEPENDIZA');x.store.corruptView('ENTITY:ENTITY:INDEPENDIZA');assert.equal(x.store.readDerivedView('ENTITY:ENTITY:INDEPENDIZA').status,'INVALID');assert.equal(x.store.resolveEntity('Independiza').entity.id,'ENTITY:INDEPENDIZA');x.store.regenerateEntityView('ENTITY:INDEPENDIZA');assert.equal(x.store.readDerivedView('ENTITY:ENTITY:INDEPENDIZA').status,'VALID');}finally{x.done();}});
