import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {CoreStore} from '../src/core-store.mjs';
import {DeterministicWorker} from '../src/deterministic-worker.mjs';
import {RoleInterface} from '../src/role-interface.mjs';
import {LocalCommandQueue} from '../src/local-role-client.mjs';

const stamp='2026-08-31T12:00:00.000Z';let sequence=0;
const credentials={CLAUDIO:'dev-credential-claudio',DGA:'dev-credential-dga',GABY_CHAT:'dev-credential-gaby-chat',GABY_CW:'dev-credential-gaby-cw',PRODUCTOR_MUSICAL:'dev-credential-productor'};
const actors={CLAUDIO:'ACTOR:CLAUDIO',DGA:'ACTOR:DIEGO',GABY_CHAT:'ACTOR:GABY_CHAT',GABY_CW:'ACTOR:GABY_CW',PRODUCTOR_MUSICAL:'ACTOR:PRODUCTOR_MUSICAL'};
function setup(options={}){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cf2-stage5-'));const store=new CoreStore(path.join(dir,'core.db'));const api=new RoleInterface(store,options);return{dir,store,api,client:role=>api.client(credentials[role]),done(){store.close();fs.rmSync(dir,{recursive:true,force:true});}};}
function cmd(role,command_type,payload,extra={}){const i=++sequence;return{command_id:`CMD:ROLE:${i}`,command_type,actor_id:actors[role],actor_role:role,issued_at:stamp,idempotency_key:extra.idempotency_key??`role-${i}`,correlation_id:extra.correlation_id??`CORR:${i}`,payload,...extra};}
function task(id,responsible_role,state='OPEN',extra={}){return{id,type:'TASK',status:state,created_at:stamp,updated_at:stamp,basis_ref:['stage5'],action:'REVIEW',state,responsible_role,related_ids:[],...extra};}
function decision(id,authority='DGA_DELEGATED'){return{id,type:'DECISION',status:'CURRENT',created_at:stamp,updated_at:stamp,basis_ref:['stage5'],subject_id:'ENTITY:ROLE',decision_key:`KEY:${id}`,value:'VALUE',authority,effective_at:stamp,source_ref:'stage5'};}
function entity(){return{id:'ENTITY:ROLE',type:'ENTITY',status:'CURRENT',created_at:stamp,updated_at:stamp,basis_ref:['stage5'],entity_kind:'TRACK',canonical_name:'Role entity',aliases:['role alias']};}

test('typed read API preserves UNKNOWN and separates history',()=>{const x=setup();try{x.store.submitCommand(cmd('CLAUDIO','UPSERT_ENTITY',{object:entity()}));const dga=x.client('DGA');assert.equal(dga.request('HEALTH').data.status,'UP');assert.equal(dga.request('READ_SNAPSHOT').data.kind,'STARTUP_SNAPSHOT');assert.equal(dga.request('RESOLVE_ENTITY',{query:'role alias'}).data.status,'UNIQUE');assert.equal(dga.request('READ_CURRENT',{subject_id:'ENTITY:ROLE',property_key:'MISSING'}).data.status,'UNKNOWN');assert.equal(dga.request('READ_ENTITY_BUNDLE',{subject_id:'ENTITY:ROLE'}).data.status,'CURRENT');const history=dga.request('READ_HISTORY',{subject_id:'ENTITY:ROLE',property_key:'MISSING'}).data;assert.ok(Array.isArray(history.decisions));assert.ok(Array.isArray(history.audit));}finally{x.done();}});

test('credential binds actor server-side and client identity declaration is rejected',()=>{const x=setup();try{const response=x.api.request({request_id:'REQ:IMPERSONATE',operation:'READ_SNAPSHOT',actor_id:'ACTOR:CLAUDIO',actor_role:'CLAUDIO'},{credential:credentials.GABY_CHAT});assert.equal(response.reason_code,'ACTOR_MISMATCH');assert.equal(response.actor_id,actors.GABY_CHAT);assert.equal(x.store.getAccessAudit().at(-1).actor_id,actors.GABY_CHAT);}finally{x.done();}});

test('missing or invalid credential fails closed without exposing credential in audit',()=>{const x=setup();try{const response=x.api.request({request_id:'REQ:NOAUTH',operation:'READ_SNAPSHOT'},{credential:'top-secret-invalid'});assert.equal(response.reason_code,'AUTHENTICATION_REQUIRED');assert.doesNotMatch(JSON.stringify(x.store.getAccessAudit()),/top-secret-invalid/);}finally{x.done();}});

test('command actor mismatch cannot impersonate Claudio',()=>{const x=setup();try{const command=cmd('CLAUDIO','CREATE_TASK',{object:task('TASK:FAKE','CLAUDIO')});const result=x.client('GABY_CHAT').submitCommand(command);assert.equal(result.reason_code,'ACTOR_MISMATCH');assert.equal(x.store.getObject('TASK:FAKE'),null);}finally{x.done();}});

test('DGA permission is distinct from delegated authority',()=>{const x=setup();try{const dga=x.client('DGA');const missing=dga.submitCommand(cmd('DGA','RECORD_DECISION',{object:decision('DECISION:NOREF'),authority_domain:'DGA_DELEGATED'}));assert.equal(missing.reason_code,'AUTHORITY_REQUIRED');const valid=dga.submitCommand(cmd('DGA','RECORD_DECISION',{object:decision('DECISION:DGA'),authority_domain:'DGA_DELEGATED'},{authority_ref:'DELEGATION:DGA:DEV'}));assert.equal(valid.ok,true);assert.equal(x.store.getObject('DECISION:DGA').authority,'DGA_DELEGATED');}finally{x.done();}});

test('Gaby Chat is limited to marketing delegation and cannot claim Claudio authority',()=>{const x=setup();try{const chat=x.client('GABY_CHAT');const excessive=chat.submitCommand(cmd('GABY_CHAT','RECORD_DECISION',{object:decision('DECISION:HIGH','CLAUDIO_DIRECT'),authority_domain:'MARKETING'},{authority_ref:'DELEGATION:MARKETING:DEV'}));assert.equal(excessive.reason_code,'AUTHORITY_REQUIRED');const allowed=chat.submitCommand(cmd('GABY_CHAT','RECORD_DECISION',{object:decision('DECISION:MKT'),authority_domain:'MARKETING'},{authority_ref:'DELEGATION:MARKETING:DEV'}));assert.equal(allowed.ok,true);}finally{x.done();}});

test('Gaby CW command outside policy is ROLE_FORBIDDEN',()=>{const x=setup();try{const result=x.client('GABY_CW').submitCommand(cmd('GABY_CW','UPSERT_ENTITY',{object:entity()}));assert.equal(result.reason_code,'ROLE_FORBIDDEN');}finally{x.done();}});

test('Productor Musical remains distinct from DGA and needs artistic authority',()=>{const x=setup();try{const producer=x.client('PRODUCTOR_MUSICAL');const wrong=producer.submitCommand(cmd('PRODUCTOR_MUSICAL','RECORD_DECISION',{object:decision('DECISION:PROD:BAD'),authority_domain:'DGA_DELEGATED'},{authority_ref:'DELEGATION:DGA:DEV'}));assert.equal(wrong.reason_code,'AUTHORITY_REQUIRED');const good=producer.submitCommand(cmd('PRODUCTOR_MUSICAL','RECORD_DECISION',{object:decision('DECISION:PROD'),authority_domain:'ARTISTIC_PRODUCTION'},{authority_ref:'DELEGATION:PRODUCER:DEV'}));assert.equal(good.ok,true);assert.equal(good.actor_role,'PRODUCTOR_MUSICAL');}finally{x.done();}});

test('verification requires evidence and audit contains refs but no credential',()=>{const x=setup();try{const base={id:'VERIFICATION:ROLE',type:'VERIFICATION',status:'CURRENT',created_at:stamp,updated_at:stamp,basis_ref:['stage5'],subject_id:'ENTITY:ROLE',attribute:'REMOTE_FACT',value:true,class:'FIJO',verified_at:stamp,verified_by:'GABY_CHAT'};const noEvidence=x.client('GABY_CHAT').submitCommand(cmd('GABY_CHAT','RECORD_VERIFICATION',{object:base}));assert.equal(noEvidence.reason_code,'EVIDENCE_REQUIRED');const yes=x.client('GABY_CHAT').submitCommand(cmd('GABY_CHAT','RECORD_VERIFICATION',{object:{...base,id:'VERIFICATION:ROLE:OK',evidence_ref:'EVIDENCE:REMOTE:1'}}));assert.equal(yes.ok,true);const audit=JSON.stringify(x.store.getAccessAudit());assert.match(audit,/EVIDENCE:REMOTE:1/);assert.doesNotMatch(audit,/dev-credential/);}finally{x.done();}});

test('accepted command exposes typed receipt and status is not falsely DONE',()=>{const x=setup();try{const command=cmd('GABY_CHAT','CREATE_TASK',{object:task('TASK:CHAT','GABY_CHAT')});const accepted=x.client('GABY_CHAT').submitCommand(command);assert.equal(accepted.data.command_status,'ACCEPTED');assert.notEqual(accepted.data.command_status,'DONE');assert.ok(accepted.data.event_ref);const status=x.client('GABY_CHAT').request('READ_COMMAND_STATUS',{command_id:command.command_id});assert.equal(status.data.status,'ACCEPTED');assert.equal(status.data.correlation_id,command.correlation_id);}finally{x.done();}});

test('same command and idempotency key produces one logical change',()=>{const x=setup();try{const command=cmd('GABY_CHAT','CREATE_TASK',{object:task('TASK:IDEMP','GABY_CHAT')},{idempotency_key:'STAGE5:IDEMP'});const a=x.client('GABY_CHAT').submitCommand(command);const b=x.client('GABY_CHAT').submitCommand(command);assert.equal(a.ok,true);assert.equal(b.ok,true);assert.equal(x.store.getAudit().filter(row=>row.command_id===command.command_id).length,1);assert.equal(x.store.getOutbox().length,1);}finally{x.done();}});

test('VERSION_CONFLICT remains typed and leaves Core consistent',()=>{const x=setup();try{const dga=x.client('DGA');const first=dga.submitCommand(cmd('DGA','CREATE_TASK',{object:task('TASK:VERSION:ONE','DGA')},{expected_state_version:0}));assert.equal(first.ok,true);const stale=dga.submitCommand(cmd('DGA','CREATE_TASK',{object:task('TASK:VERSION:TWO','DGA')},{expected_state_version:0}));assert.equal(stale.reason_code,'VERSION_CONFLICT');assert.equal(x.store.getObject('TASK:VERSION:TWO'),null);}finally{x.done();}});

test('T17 cloud continuity isolates unavailable local capability',()=>{const x=setup({localAvailable:false});try{const cloud=x.client('GABY_CHAT');assert.equal(cloud.request('HEALTH').ok,true);assert.equal(cloud.request('READ_SNAPSHOT').ok,true);const independent=cloud.submitCommand(cmd('GABY_CHAT','CREATE_TASK',{object:task('TASK:CLOUD:INDEPENDENT','GABY_CHAT')}));assert.equal(independent.ok,true);const localTask=cloud.submitCommand(cmd('GABY_CHAT','CREATE_TASK',{object:task('TASK:CLOUD:LOCAL','GABY_CHAT','BLOCKED',{requires_local_capability:true,block_reason:'BLOCKED_LOCAL_CAPABILITY'})}));assert.equal(localTask.ok,true);assert.equal(cloud.request('REQUEST_LOCAL_CAPABILITY').reason_code,'BLOCKED_LOCAL_CAPABILITY');assert.equal(x.store.getObject('TASK:CLOUD:INDEPENDENT').state,'OPEN');assert.equal(x.store.getObject('TASK:CLOUD:LOCAL').state,'BLOCKED');}finally{x.done();}});

test('T18 local disconnect, restart and idempotent reconnect deliver only pending work',()=>{const x=setup();try{const queuePath=path.join(x.dir,'gaby-cw-transport.json');const command=cmd('GABY_CW','CREATE_TASK',{object:task('TASK:CW:OFFLINE','GABY_CW')},{idempotency_key:'CW:OFFLINE:ONE'});let queue=new LocalCommandQueue(queuePath);queue.enqueue(command);queue.enqueue(command);assert.equal(queue.pending().length,1);assert.equal(x.store.getObject('TASK:CW:OFFLINE'),null);queue=new LocalCommandQueue(queuePath);const results=queue.flush(x.client('GABY_CW'));assert.equal(results.length,1);assert.equal(results[0].ok,true);assert.equal(queue.pending().length,0);assert.equal(queue.flush(x.client('GABY_CW')).length,0);assert.equal(x.store.getAudit().filter(row=>row.command_id===command.command_id).length,1);}finally{x.done();}});

test('local queue is transport only and persists no credential or acceptance while offline',()=>{const x=setup();try{const queuePath=path.join(x.dir,'transport.json');const command=cmd('GABY_CW','CREATE_TASK',{object:task('TASK:TRANSPORT','GABY_CW')});const queue=new LocalCommandQueue(queuePath);const queued=queue.enqueue(command);assert.equal(queued.status,'PENDING');const raw=fs.readFileSync(queuePath,'utf8');assert.doesNotMatch(raw,/dev-credential/);assert.doesNotMatch(raw,/ACCEPTED/);assert.equal(x.store.getObject('TASK:TRANSPORT'),null);}finally{x.done();}});

test('clients expose no CoreStore, database path, outbox or jobs',()=>{const x=setup();try{const client=x.client('GABY_CHAT');for(const key of ['store','db','dbPath','outbox','jobs'])assert.equal(Object.prototype.hasOwnProperty.call(client,key),false);assert.equal(client.request('READ_TASK_VIEW').ok,true);}finally{x.done();}});

test('Codex and Claude Code offline do not affect deterministic runtime',async()=>{const x=setup();try{x.store.submitCommand(cmd('CLAUDIO','UPSERT_ENTITY',{object:entity()}));const worker=new DeterministicWorker(x.store);await worker.runOnce({at:stamp});assert.equal(x.client('DGA').request('READ_SNAPSHOT').ok,true);assert.equal(x.store.readDerivedView('SNAPSHOT:DEFAULT').status,'VALID');assert.equal(Object.keys(credentials).includes('CODEX'),false);assert.equal(Object.keys(credentials).includes('CLAUDE_CODE'),false);}finally{x.done();}});

test('Claudio relay is zero for cloud read-command-status path',()=>{const x=setup();try{const chat=x.client('GABY_CHAT');assert.equal(chat.request('READ_SNAPSHOT').ok,true);const command=cmd('GABY_CHAT','CREATE_TASK',{object:task('TASK:NO:RELAY','GABY_CHAT')});assert.equal(chat.submitCommand(command).ok,true);assert.equal(chat.request('READ_COMMAND_STATUS',{command_id:command.command_id}).data.status,'ACCEPTED');const actorsSeen=new Set(x.store.getAccessAudit().map(row=>row.actor_id));assert.deepEqual([...actorsSeen],[actors.GABY_CHAT]);}finally{x.done();}});
