import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { CoreStore } from '../src/core-store.mjs';
import { ShadowRuntime, SelectiveMigrator, classifyFinding, compareLogical, createMigrationBaseline } from '../src/shadow.mjs';

const stamp='2026-08-29T19:00:00.000Z';let n=0;
function command(object){return {command_id:`CMD:SHADOW:${++n}`,command_type:'UPSERT_ENTITY',actor_id:'ACTOR:CLAUDIO',actor_role:'CLAUDIO',issued_at:stamp,idempotency_key:`shadow-${n}`,payload:{object}};}
function entity(id){return {id,type:'ENTITY',status:'CURRENT',created_at:stamp,updated_at:stamp,basis_ref:['shadow'],entity_kind:'TRACK',canonical_name:id,aliases:[]};}
function setup(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cf2-shadow-'));const store=new CoreStore(path.join(dir,'core.db'));return {dir,store,done(){store.close();fs.rmSync(dir,{recursive:true,force:true});}};}

test('baseline seals only explicit complete source bytes without writing CF1',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cf2-baseline-'));try{const file=path.join(dir,'source.md');fs.writeFileSync(file,'read only baseline');const baseline=createMigrationBaseline({at:stamp,source_manifest_ref:'MANIFEST:DEV',artifacts:[{ref:'CF1:MAESTRO',path:file}],schedulers:[{name:'legacy',state:'DISABLED'}],mappings:[{artifact_id:'A:1',A_path:'read-only.md',C_file_id:'C:EXACT',replication_mode:'A_TO_C_EXACT_ID',byte_preserving:true}]});assert.equal(baseline.artifacts[0].bytes,18);assert.equal(baseline.mode,'CF1_READ_ONLY');assert.ok(baseline.baseline_digest);assert.equal(fs.readFileSync(file,'utf8'),'read only baseline');}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('baseline fails closed on a source that could be truncated or is not an explicit regular file',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cf2-baseline-'));try{const file=path.join(dir,'big.md');fs.writeFileSync(file,'1234');assert.throws(()=>createMigrationBaseline({artifacts:[{ref:'CF1:BIG',path:file}],maxSourceBytes:3}),error=>error.reason_code==='SOURCE_READ_LIMIT_EXCEEDED');assert.throws(()=>createMigrationBaseline({artifacts:[{ref:'CF1:DIR',path:dir}]}),error=>error.reason_code==='SOURCE_NOT_REGULAR_FILE');}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('baseline CLI accepts only an explicit manifest and emits no CF1 write',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cf2-baseline-cli-'));try{fs.writeFileSync(path.join(dir,'current.md'),'complete source');const manifest=path.join(dir,'manifest.json');fs.writeFileSync(manifest,JSON.stringify({source_manifest_ref:'CF1:CLI',artifacts:[{ref:'CF1:CURRENT',path:'current.md'}]}));const run=spawnSync(process.execPath,['scripts/stage6-build-baseline.mjs',manifest],{cwd:path.resolve(import.meta.dirname,'..'),encoding:'utf8'});assert.equal(run.status,0);assert.equal(JSON.parse(run.stdout).artifacts[0].sha256.length,64);assert.equal(fs.readFileSync(path.join(dir,'current.md'),'utf8'),'complete source');}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('exact mappings require the authorized remote ID and byte-preserving exact mode',()=>assert.throws(()=>createMigrationBaseline({mappings:[{artifact_id:'A',A_path:'x',replication_mode:'A_TO_C_EXACT_ID',byte_preserving:true}]}),error=>error.reason_code==='INVALID_BASELINE_MANIFEST'));
test('selective importer promotes only authoritative current; ambiguity stays non-authoritative',()=>{const x=setup();try{const migrator=new SelectiveMigrator(x.store);const report=migrator.import([{classification:'AUTHORITATIVE_CURRENT',command:command(entity('ENTITY:CURRENT')),evidence_ref:'source:current'},{classification:'CANDIDATE',subject:'ENTITY:ATARAXIA',evidence_ref:'source:ambiguous'},{classification:'UNKNOWN',subject:'ENTITY:NEW',evidence_ref:'source:unknown'}]);assert.equal(report.imported.length,1);assert.equal(report.candidates.length,1);assert.equal(report.unknown.length,1);assert.equal(x.store.getObject('ENTITY:CURRENT').id,'ENTITY:CURRENT');assert.equal(x.store.getObject('ENTITY:ATARAXIA'),null);}finally{x.done();}});
test('logical comparator compares typed IDs and preserves missing records as UNKNOWN',()=>{const report=compareLogical({tasks:[{id:'TASK:ONE',state:'OPEN'}],mappings:[{artifact_id:'A',C_file_id:'C:1'}]},{tasks:[{id:'TASK:ONE',state:'BLOCKED'}]});assert.equal(report.conflict,1);assert.equal(report.unknown,1);assert.equal(report.discrepancies.find(x=>x.object==='mappings:A').CF2.status,'UNKNOWN');});
test('shadow records only WOULD_DO and does not close a 24-hour soak early',()=>{let tick=0;const times=['2026-09-01T19:00:00.000Z','2026-09-01T19:00:01.000Z','2026-09-01T19:00:02.000Z','2026-09-02T18:59:59.999Z','2026-09-02T19:00:00.000Z','2026-09-02T19:00:01.000Z'];const shadow=new ShadowRuntime({at:()=>times[tick++]});assert.equal(shadow.start().mode,'SHADOW_READ');assert.equal(shadow.observe({baseline:{artifacts:[{artifact_id:'A'}]},current:{artifacts:[{artifact_id:'A'}]}}).comparison.result,'EQUAL');const action=shadow.wouldDo('REPLICATE',{artifact_id:'A'});assert.equal(action.action,'WOULD_REPLICATE');assert.equal(shadow.soakStatus().result,'SOAK_DURATION_PENDING');assert.equal(shadow.soakStatus().result,'SOAK_DURATION_MET');assert.equal(shadow.report().no_side_effect,true);});
test('shadow transport dedupes metadata delivery without relying on a content revision',()=>{let tick=0;const shadow=new ShadowRuntime({at:()=>`2026-09-01T19:00:0${tick++}.000Z`});shadow.start();const args={file_id:'REQ',observed_name:'renamed.gate',modified_time:'M',request_id:'R',nonce:'N',baseline:{},current:{}};assert.notEqual(shadow.transportObservation(args).result,'TRANSPORT_DUPLICATE_IGNORED');assert.equal(shadow.transportObservation(args).result,'TRANSPORT_DUPLICATE_IGNORED');});
test('shadow soak evidence survives a CF2 restart without external effects',()=>{const x=setup();try{const id='SHADOW:DURABLE';const first=new ShadowRuntime({store:x.store,sessionId:id,baselineDigest:'BASE:1',at:()=>stamp});first.start();first.observe({baseline:{tasks:[{id:'TASK:ONE',state:'OPEN'}]},current:{tasks:[{id:'TASK:ONE',state:'OPEN'}]}});x.store.close();const restartedStore=new CoreStore(path.join(x.dir,'core.db'));const resumed=new ShadowRuntime({store:restartedStore,sessionId:id,baselineDigest:'BASE:1',at:()=> '2026-09-02T19:00:00.000Z'});assert.equal(resumed.start().started_at,stamp);assert.equal(resumed.report().observations.length,1);assert.equal(resumed.soakStatus().result,'SOAK_DURATION_MET');restartedStore.close();}finally{try{x.store.close();}catch{}fs.rmSync(x.dir,{recursive:true,force:true});}});
test('invalid classification fails closed',()=>assert.throws(()=>classifyFinding({classification:'FALSE',evidence_ref:'x'}),error=>error.reason_code==='INVALID_MIGRATION_CLASSIFICATION'));
