import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {CoreStore} from '../src/core-store.mjs';import {RoleInterface} from '../src/role-interface.mjs';import {GoogleDriveClient,Stage5DriveBridge,validateChannel,validateRequest} from '../src/stage5-drive-bridge.mjs';
const now=Date.parse('2026-08-31T12:00:00Z');
class Drive{constructor(){this.contents=new Map([['REQ',Buffer.from('{}')],['RESP',Buffer.from('old')]]);this.metas=new Map([['REQ',{id:'REQ',mimeType:'text/plain',parents:['FOLDER'],version:'1',headRevisionId:'REV1',lastModifyingUser:{permissionId:'P1'}}],['RESP',{id:'RESP',mimeType:'text/plain',parents:['FOLDER'],version:'1',headRevisionId:'R0',lastModifyingUser:{permissionId:'P1'}}]]);this.writes=0;}about(){return{user:{permissionId:'P1'}};}metadata(id){return structuredClone(this.metas.get(id));}download(id){return this.contents.get(id);}update(id,b){this.writes++;this.contents.set(id,Buffer.from(b));return{id,version:String(this.writes+1)};}watch(){return{resourceId:'RESOURCE',expiration:String(now+3600000)}};}
function setup(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cf2-stage5-cloud-test-'));const store=new CoreStore(path.join(dir,'db.sqlite'));const drive=new Drive();const roles=new RoleInterface(store,{localAvailable:false});const bridge=new Stage5DriveBridge({drive,roleInterface:roles,gateInstanceId:'GATE',clock:()=>now});return{dir,store,drive,bridge,async boot(){return bridge.bootstrap({folderId:'FOLDER',requestId:'REQ',responseId:'RESP',webhookUrl:'https://gate.example/webhooks/drive'});},done(){store.close();fs.rmSync(dir,{recursive:true,force:true});}};}
const headers=(x={})=>({'x-goog-channel-id':'CHAN','x-goog-channel-token':'TOKEN','x-goog-resource-id':'RESOURCE','x-goog-resource-state':'update',...x});
const request=(operation,extra={})=>Buffer.from(JSON.stringify({gate:'STAGE5',request_id:`REQ_${operation}`,operation,nonce:`NONCE_${operation}`,issued_at:'2026-08-31T12:00:00Z',ttl_seconds:300,non_productive:true,...extra}));
test('channel validation rejects wrong token/id/resource and ignores sync',()=>{const e={channelId:'CHAN',channelToken:'TOKEN',resourceId:'RESOURCE'};assert.equal(validateChannel(headers(),e).ok,true);assert.equal(validateChannel(headers({'x-goog-channel-token':'bad'}),e).code,'CHANNEL_TOKEN_INVALID');assert.equal(validateChannel(headers({'x-goog-channel-id':'bad'}),e).code,'CHANNEL_ID_INVALID');assert.equal(validateChannel(headers({'x-goog-resource-id':'bad'}),e).code,'RESOURCE_ID_INVALID');assert.equal(validateChannel(headers({'x-goog-resource-state':'sync'}),e).code,'INITIAL_SYNC_IGNORED');});
test('request validation fails closed for spoof, invalid json, stale ttl, nonce shape and operation',()=>{assert.equal(validateRequest(Buffer.from('x'),{nowMs:now}).code,'INVALID_SCHEMA');assert.equal(validateRequest(request('READ_SNAPSHOT',{actor_role:'CLAUDIO'}),{nowMs:now}).code,'ACTOR_MISMATCH');assert.equal(validateRequest(request('READ_SNAPSHOT',{issued_at:'2026-08-31T11:00:00Z'}),{nowMs:now}).code,'TTL_EXPIRED');assert.equal(validateRequest(request('SHELL'),{nowMs:now}).code,'INVALID_SCHEMA');});
test('OAuth URL is PKCE, drive.file only, and contains no client secret',()=>{const client=new GoogleDriveClient({clientId:'CLIENT',clientSecret:'TOP_SECRET',redirectUri:'https://gate.example/oauth/google/callback',fetchImpl:()=>{throw new Error('unused');}});const url=client.authorizationUrl({state:'STATE',codeChallenge:'CHALLENGE'});assert.match(url,/drive.file/);assert.match(url,/code_challenge=CHALLENGE/);assert.doesNotMatch(url,/TOP_SECRET|auth%2Fdrive(?:&|$)/);});
test('bootstrap records baseline, scope and staging-only principal fingerprint',async()=>{const x=setup();try{const ready=await x.boot();assert.equal(ready.baseline_revision.headRevisionId,'REV1');assert.equal(ready.actor_binding_scope,'STAGING_CHANNEL_ONLY');assert.equal(ready.oauth_scope,'https://www.googleapis.com/auth/drive.file');assert.equal(ready.watch_active,true);}finally{x.done();}});
test('baseline revision and initial sync never execute or write response',async()=>{const x=setup();try{await x.boot();x.bridge.channel={channelId:'CHAN',channelToken:'TOKEN',resourceId:'RESOURCE'};assert.equal((await x.bridge.webhook(headers({'x-goog-resource-state':'sync'}))).http,204);assert.equal((await x.bridge.webhook(headers())).result.result,'BASELINE_IGNORED');assert.equal(x.drive.writes,0);}finally{x.done();}});
test('lastModifyingUser mismatch is fail-closed and writes sanitized response',async()=>{const x=setup();try{await x.boot();x.bridge.channel={channelId:'CHAN',channelToken:'TOKEN',resourceId:'RESOURCE'};x.drive.metas.get('REQ').version='2';x.drive.metas.get('REQ').headRevisionId='REV2';x.drive.metas.get('REQ').lastModifyingUser.permissionId='OTHER';const out=await x.bridge.webhook(headers());assert.equal(out.result.result,'ACTOR_BINDING_UNPROVEN');assert.doesNotMatch(x.drive.contents.get('RESP').toString(),/OTHER|TOKEN/);}finally{x.done();}});
test('wrong request parent fails before parsing content',async()=>{const x=setup();try{await x.boot();x.bridge.channel={channelId:'CHAN',channelToken:'TOKEN',resourceId:'RESOURCE'};x.drive.metas.get('REQ').version='2';x.drive.metas.get('REQ').headRevisionId='REV2';x.drive.metas.get('REQ').parents=['OTHER_FOLDER'];const out=await x.bridge.webhook(headers());assert.equal(out.result.result,'REMOTE_READ_INVALID');assert.equal(x.store.getObject('TASK:STAGE5:SYNTHETIC:CLOUD'),null);assert.equal(x.store.getAccessAudit().some(row=>row.detail?.command_id),false);}finally{x.done();}});
test('READ uses real RoleInterface and writes response only to exact response ID',async()=>{const x=setup();try{await x.boot();x.bridge.channel={channelId:'CHAN',channelToken:'TOKEN',resourceId:'RESOURCE'};x.drive.metas.get('REQ').version='2';x.drive.metas.get('REQ').headRevisionId='REV2';x.drive.contents.set('REQ',request('READ_SNAPSHOT'));const out=await x.bridge.webhook(headers());assert.equal(out.result.result,'PASS');assert.equal(out.result.actor_role,'DGA');assert.equal(x.drive.writes,1);assert.ok(x.drive.contents.has('RESP'));}finally{x.done();}});
test('COMMAND traverses RoleInterface, STATUS is separate, and idempotency creates one task',async()=>{const x=setup();try{await x.boot();x.bridge.channel={channelId:'CHAN',channelToken:'TOKEN',resourceId:'RESOURCE'};const submit=request('COMMAND_SUBMIT',{request_id:'REQ_COMMAND_1',nonce:'NONCE_1',command_id:'COMMAND:STAGE5:CLOUD:DGA:001',idempotency_key:'IDEMP:STAGE5:CLOUD:001'});x.drive.metas.get('REQ').version='2';x.drive.metas.get('REQ').headRevisionId='REV2';x.drive.contents.set('REQ',submit);assert.equal((await x.bridge.webhook(headers())).result.status,'ACCEPTED');x.drive.metas.get('REQ').version='3';x.drive.metas.get('REQ').headRevisionId='REV3';x.drive.contents.set('REQ',request('COMMAND_SUBMIT',{request_id:'REQ_COMMAND_2',nonce:'NONCE_2',command_id:'COMMAND:STAGE5:CLOUD:DGA:001',idempotency_key:'IDEMP:STAGE5:CLOUD:001'}));assert.equal((await x.bridge.webhook(headers())).result.result,'PASS');assert.equal(x.store.getAudit().filter(a=>a.command_id==='COMMAND:STAGE5:CLOUD:DGA:001').length,1);x.drive.metas.get('REQ').version='4';x.drive.metas.get('REQ').headRevisionId='REV4';x.drive.contents.set('REQ',request('READ_COMMAND_STATUS',{nonce:'NONCE_3',command_id:'COMMAND:STAGE5:CLOUD:DGA:001'}));assert.equal((await x.bridge.webhook(headers())).result.status,'ACCEPTED');}finally{x.done();}});
test('nonce replay is rejected and secrets never appear in response/audit',async()=>{const x=setup();try{await x.boot();x.bridge.channel={channelId:'CHAN',channelToken:'TOKEN',resourceId:'RESOURCE'};x.drive.metas.get('REQ').version='2';x.drive.metas.get('REQ').headRevisionId='REV2';x.drive.contents.set('REQ',request('READ_SNAPSHOT',{nonce:'SAME_NONCE'}));await x.bridge.webhook(headers());x.drive.metas.get('REQ').version='3';x.drive.metas.get('REQ').headRevisionId='REV3';const out=await x.bridge.webhook(headers());assert.equal(out.result.result,'NONCE_REPLAY');assert.doesNotMatch(JSON.stringify(out),/TOKEN|authorization|refresh_token/i);}finally{x.done();}});
test('Render deploy is exact, plural, single-shot, reconciled and pinned',()=>{const workflow=fs.readFileSync(new URL('../.github/workflows/render-stage5-cloud-gate.yml',import.meta.url),'utf8');assert.match(workflow,/on:\s*\n\s*workflow_dispatch:/);assert.doesNotMatch(workflow,/\n\s*push:/);assert.match(workflow,/STAGING_ID='srv-daaqc2u7bikc73fkg44g'/);assert.match(workflow,/TARGET_COMMIT='8ca2c34fa864d85e79f617ed31eed1921f55ced1'/);assert.match(workflow,/call\('GET',f'\/services\/\{STAGING_ID\}'\)/);assert.equal((workflow.match(/call\('POST',f'\/services\/\{STAGING_ID\}\/deploys'/g)??[]).length,1);assert.doesNotMatch(workflow,/\/deploy['"]/);assert.doesNotMatch(workflow,/deployMode|clearCache|imageUrl|call\('PATCH'|call\('POST','\/services'/);assert.match(workflow,/\{'commitId':TARGET_COMMIT\}/);assert.match(workflow,/DEPLOY_RESULT_AMBIGUOUS_NO_RETRY/);assert.match(workflow,/find_target_deploy\(\)/);assert.match(workflow,/deploys\/\{deploy_id\}/);assert.match(workflow,/STAGE5_HEALTH=PASS/);assert.match(workflow,/PRODUCTION_DATABASE_BINDING_PRESENT/);assert.doesNotMatch(workflow,/print\([^\n]*(RENDER_API_KEY|Authorization)/);});
test('OAuth callback uses normalized Render URL, explicit DEV localhost and fails closed otherwise',()=>{const source=fs.readFileSync(new URL('../src/stage5-cloud-gate-server.mjs',import.meta.url),'utf8');assert.match(source,/configured\.replace\(\/\\\/\+\$\/,''\)/);assert.match(source,/\['development','test'\]\.includes\(env\.NODE_ENV\)/);assert.match(source,/RENDER_EXTERNAL_URL_REQUIRED/);assert.doesNotMatch(source,/RENDER_EXTERNAL_URL\?\?`http:\/\/127\.0\.0\.1/);});
