import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { CoreStore } from '../src/core-store.mjs';
import { AdapterError, DriveIdAdapter, FileSystemAAdapter, InMemoryDriveStaging, ReplicationService } from '../src/staging-adapters.mjs';

const stamp='2026-08-29T17:00:00.000Z';
function setup({client,allowedIds=['C:AUTHORIZED']}={}) { const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cf2-stage4-')); const root=path.join(dir,'A-STAGING'); fs.mkdirSync(root); fs.writeFileSync(path.join(root,'artifact.txt'),'CF2 staging bytes v1\n'); const store=new CoreStore(path.join(dir,'core.db')); const transport=client ?? new InMemoryDriveStaging([{id:'C:AUTHORIZED',title:'same-name.txt',bytes:'old',mime_type:'text/plain',parent_id:'FOLDER:STAGING'},{id:'C:HOMONYM',title:'same-name.txt',bytes:'homonym must remain',mime_type:'text/plain',parent_id:'FOLDER:STAGING'}]); const sourceA=new FileSystemAAdapter(root); const remoteC=new DriveIdAdapter(transport,{authorizedIds:allowedIds}); const service=new ReplicationService({registry:store,sourceA,remoteC,clock:()=>stamp}); const mapping={mapping_id:'MAPPING:STAGE4:ONE',artifact_id:'ARTIFACT:STAGE4:ONE',generation:'GEN:1',A_path:'artifact.txt',C_file_id:'C:AUTHORIZED',environment:'STAGING',status:'AUTHORIZED',created_at:stamp,updated_at:stamp,basis_ref:['test']}; return {dir,root,store,transport,sourceA,remoteC,service,mapping,addMapping(){return store.registerStagingMapping(mapping);},done(){store.close();fs.rmSync(dir,{recursive:true,force:true});}}; }

test('adapter A permits only explicit staging-relative files',()=>{const x=setup();try { assert.equal(x.sourceA.metadata('artifact.txt').bytes,21); assert.throws(()=>x.sourceA.read('../outside.txt'),error=>error.reason_code==='FAIL_CLOSED'); assert.throws(()=>x.sourceA.read(path.resolve(x.root,'artifact.txt')),error=>error.reason_code==='FAIL_CLOSED'); } finally{x.done();}});

test('T13: absent mapping rejects operation; name has no fallback',()=>{const x=setup();try { assert.throws(()=>x.service.replicate({artifact_id:'ARTIFACT:BY_NAME',generation:'GEN:1',name:'same-name.txt'}),error=>error instanceof AdapterError && error.reason_code==='MAPPING_MISSING'); } finally{x.done();}});

test('T14: A to C exact-ID write/readback emits byte-preserving proof',()=>{const x=setup();try { x.addMapping(); const result=x.service.replicate({artifact_id:x.mapping.artifact_id,generation:'GEN:1'}); assert.equal(result.result,'SYNC_VERIFIED'); assert.equal(result.proof.C_file_id,'C:AUTHORIZED'); assert.equal(result.bytes_A,result.bytes_C); assert.equal(result.sha256_A,result.sha256_C); assert.equal(x.store.listReplicationProofs().length,1); } finally{x.done();}});

test('T15: B diagnostic cannot prove A to C',()=>{const x=setup();try { assert.deepEqual(x.service.diagnoseB(),{result:'NO_SYNC',reason_code:'REPLICATION_NOT_PROVEN',authoritative:false}); assert.equal(x.store.listReplicationProofs().length,0); } finally{x.done();}});

test('T16: newer homonym is ignored; only mapping C ID participates',()=>{const x=setup();try { x.addMapping(); const before=x.transport.readById('C:HOMONYM').bytes.toString(); const result=x.service.replicate({artifact_id:x.mapping.artifact_id,generation:'GEN:1'}); assert.equal(result.result,'SYNC_VERIFIED'); assert.equal(x.transport.readById('C:HOMONYM').bytes.toString(),before); assert.equal(x.transport.readById('C:AUTHORIZED').bytes.toString(),'CF2 staging bytes v1\n'); } finally{x.done();}});

test('unauthorized or wrong C ID is fail-closed and creates no proof',()=>{const x=setup({allowedIds:['C:OTHER']});try { x.addMapping(); const result=x.service.replicate({artifact_id:x.mapping.artifact_id,generation:'GEN:1'}); assert.equal(result.reason_code,'UNAUTHORIZED_C_ID'); assert.equal(x.store.listReplicationProofs().length,0); assert.equal(x.store.listReplicationAttempts().length,1); } finally{x.done();}});

test('empty readback and hash mismatch fail closed without proof',()=>{const empty={writeById:id=>({id}),readById:id=>({id,bytes:Buffer.alloc(0)}),metadataById:id=>({id})}; const a=setup({client:empty});try { a.addMapping(); assert.equal(a.service.replicate({artifact_id:a.mapping.artifact_id,generation:'GEN:1'}).reason_code,'READBACK_EMPTY'); assert.equal(a.store.listReplicationProofs().length,0); } finally{a.done();} const altered={writeById:id=>({id}),readById:id=>({id,bytes:Buffer.from('altered')}),metadataById:id=>({id})}; const b=setup({client:altered});try { b.addMapping(); assert.equal(b.service.replicate({artifact_id:b.mapping.artifact_id,generation:'GEN:1'}).reason_code,'HASH_MISMATCH'); assert.equal(b.store.listReplicationProofs().length,0); } finally{b.done();}});

test('A changing after seal returns SUPERSEDED_GENERATION and never syncs it',()=>{let target; const changing={writeById:id=>{fs.writeFileSync(target,'CF2 staging bytes v2\n');return {id};},readById:id=>({id,bytes:Buffer.from('CF2 staging bytes v1\n')}),metadataById:id=>({id})}; const x=setup({client:changing});try { target=path.join(x.root,'artifact.txt'); x.addMapping(); const result=x.service.replicate({artifact_id:x.mapping.artifact_id,generation:'GEN:1'}); assert.equal(result.reason_code,'SUPERSEDED_GENERATION'); assert.equal(x.store.listReplicationProofs().length,0); } finally{x.done();}});

test('same stable generation retry is idempotent and B absence changes nothing',()=>{const x=setup();try { x.addMapping(); const one=x.service.replicate({artifact_id:x.mapping.artifact_id,generation:'GEN:1'}); const two=x.service.replicate({artifact_id:x.mapping.artifact_id,generation:'GEN:1'}); assert.equal(one.proof.proof_id,two.proof.proof_id); assert.equal(x.store.listReplicationProofs().length,1); assert.equal(x.service.diagnoseB().reason_code,'REPLICATION_NOT_PROVEN'); } finally{x.done();}});

test('remote unavailable remains retryable and produces no replication proof',()=>{const unavailable={writeById(){throw new AdapterError('REMOTE_NOT_PROVEN');},readById(){throw new AdapterError('REMOTE_NOT_PROVEN');},metadataById(){throw new AdapterError('REMOTE_NOT_PROVEN');}}; const x=setup({client:unavailable});try { x.addMapping(); const result=x.service.replicate({artifact_id:x.mapping.artifact_id,generation:'GEN:1'}); assert.equal(result.result,'NO_SYNC'); assert.equal(result.retryable,true); assert.equal(result.reason_code,'REMOTE_NOT_PROVEN'); assert.equal(x.store.listReplicationProofs().length,0); } finally{x.done();}});
