import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {CoreStore} from '../src/core-store.mjs';import {RoleInterface} from '../src/role-interface.mjs';import {GoogleDriveClient,Stage5DriveBridge,parseMetadataEnvelope,validateChannel} from '../src/stage5-drive-bridge.mjs';
const now=Date.parse('2026-08-31T12:00:00Z');
class Drive{constructor(){this.contents=new Map([['RESP',Buffer.from('old')]]);this.metas=new Map([['REQ',{id:'REQ',name:'STAGE5_GATE_REQUEST.json',mimeType:'text/plain',parents:['FOLDER'],modifiedTime:'2026-08-31T12:00:00.000Z',version:'1',headRevisionId:'REV1',lastModifyingUser:{permissionId:'P1'}}],['RESP',{id:'RESP',name:'STAGE5_GATE_RESPONSE.json',mimeType:'text/plain',parents:['FOLDER'],modifiedTime:'2026-08-31T12:00:00.000Z',version:'1',headRevisionId:'R0',lastModifyingUser:{permissionId:'P1'}}]]);this.writes=0;}about(){return{user:{permissionId:'P1'}};}metadata(id){return structuredClone(this.metas.get(id));}update(id,b){this.writes++;this.contents.set(id,Buffer.from(b));return{id,version:String(this.writes+1)};}watch(){return{resourceId:'RESOURCE',expiration:String(now+3600000)}};rename(name,{permissionId='P1',keepContentRevision=true}={}){const m=this.metas.get('REQ');m.name=name;m.modifiedTime=`2026-08-31T12:00:0${Number(m.version)+1}.000Z`;if(!keepContentRevision){m.version=String(Number(m.version)+1);m.headRevisionId=`REV${m.version}`;}m.lastModifyingUser={permissionId};}}
function setup(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cf2-stage5-cloud-test-'));const store=new CoreStore(path.join(dir,'db.sqlite'));const drive=new Drive();const roles=new RoleInterface(store,{localAvailable:false});const logs=[];const bridge=new Stage5DriveBridge({drive,roleInterface:roles,gateInstanceId:'11111111-1111-1111-1111-111111111111',clock:()=>now,logger:{info:line=>logs.push(JSON.parse(line))}});return{dir,store,drive,bridge,logs,async boot(){return bridge.bootstrap({folderId:'FOLDER',requestId:'REQ',responseId:'RESP',webhookUrl:'https://gate.example/webhooks/drive'});},done(){store.close();fs.rmSync(dir,{recursive:true,force:true});}};}
const headers=(x={})=>({'x-goog-channel-id':'CHAN','x-goog-channel-token':'TOKEN','x-goog-resource-id':'RESOURCE','x-goog-resource-state':'update',...x});
const name=(op,id,nonce='12345678abcdef12',gate='11111111-1111-1111-1111-111111111111')=>`CF2S5__${gate}__${op}__${id}__${nonce}.gate`;
const response=x=>JSON.parse(x.drive.contents.get('RESP').toString());
test('channel accepts update only and rejects spoofed channel fields',()=>{const x={channelId:'CHAN',channelToken:'TOKEN',resourceId:'RESOURCE'};assert.equal(validateChannel(headers(),x).ok,true);assert.equal(validateChannel(headers({'x-goog-resource-state':'sync'}),x).code,'INITIAL_SYNC_IGNORED');assert.equal(validateChannel(headers({'x-goog-channel-token':'bad'}),x).code,'CHANNEL_TOKEN_INVALID');});
test('metadata grammar is finite, bounded and gate-bound',()=>{assert.equal(parseMetadataEnvelope(name('READ','REQ_A'),'11111111-1111-1111-1111-111111111111').ok,true);assert.equal(parseMetadataEnvelope('free text','11111111-1111-1111-1111-111111111111').code,'INVALID_METADATA_ENVELOPE');assert.equal(parseMetadataEnvelope(name('READ','REQ_A','12345678','22222222-2222-2222-2222-222222222222'),'11111111-1111-1111-1111-111111111111').code,'GATE_INSTANCE_MISMATCH');assert.equal(parseMetadataEnvelope('x'.repeat(241),'11111111-1111-1111-1111-111111111111').code,'INVALID_METADATA_ENVELOPE');});
test('OAuth URL is PKCE, drive.file only, and contains no client secret',()=>{const client=new GoogleDriveClient({clientId:'CLIENT',clientSecret:'TOP_SECRET',redirectUri:'https://gate.example/oauth/google/callback',fetchImpl:()=>{throw new Error('unused');}});const url=client.authorizationUrl({state:'STATE',codeChallenge:'CHALLENGE'});assert.match(url,/drive.file/);assert.match(url,/code_challenge=CHALLENGE/);assert.doesNotMatch(url,/TOP_SECRET|auth%2Fdrive(?:&|$)/);});
test('bootstrap records immutable metadata baseline, watch and four fresh exact rename envelopes',async()=>{const x=setup();try{const ready=await x.boot();assert.equal(ready.baseline_revision.file_id,'REQ');assert.equal(ready.baseline_revision.modified_time,'2026-08-31T12:00:00.000Z');assert.equal(ready.baseline_revision.headRevisionId,'REV1');assert.equal(ready.watch_active,true);assert.equal(Object.keys(ready.rename_envelopes).length,4);assert.equal(ready.rename_envelopes.READ.includes('__READ__'),true);assert.equal(ready.actor_binding_scope,'STAGING_CHANNEL_ONLY');}finally{x.done();}});
test('rename with unchanged content revision is processed once; equal baseline is ignored',async()=>{const x=setup();try{await x.boot();x.bridge.channel={channelId:'CHAN',channelToken:'TOKEN',resourceId:'RESOURCE'};assert.equal((await x.bridge.webhook(headers())).result.result,'BASELINE_IGNORED');x.drive.rename(name('READ','REQ_READ'));assert.equal(x.drive.metas.get('REQ').version,'1');assert.equal(x.drive.metas.get('REQ').headRevisionId,'REV1');await x.bridge.webhook(headers());const writes=x.drive.writes;assert.equal((await x.bridge.webhook(headers())).result.result,'TRANSPORT_DUPLICATE_IGNORED');assert.equal(x.drive.writes,writes);}finally{x.done();}});
test('metadata READ reaches RoleInterface, writes only RESPONSE exact-ID and logs sanitized stages',async()=>{const x=setup();try{await x.boot();x.bridge.channel={channelId:'CHAN',channelToken:'TOKEN',resourceId:'RESOURCE'};x.drive.rename(name('READ','REQ_READ'));const out=await x.bridge.webhook(headers());assert.equal(out.result.result,'PASS');assert.equal(response(x).operation,'READ');assert.equal(response(x).actor_role,'DGA');assert.equal(x.drive.writes,1);assert.deepEqual(x.logs.map(row=>row.event),['WEBHOOK_RECEIVED','METADATA_READBACK','ACTOR_BINDING_PASS','ENVELOPE_ACCEPTED','ROLE_INTERFACE_EXECUTED','RESPONSE_WRITE_ATTEMPT','RESPONSE_WRITE_PASS']);assert.doesNotMatch(JSON.stringify(x.logs),/authorization|token|secret/i);}finally{x.done();}});
test('metadata COMMAND traverses RoleInterface and creates one synthetic task',async()=>{const x=setup();try{await x.boot();x.bridge.channel={channelId:'CHAN',channelToken:'TOKEN',resourceId:'RESOURCE'};x.drive.rename(name('COMMAND','REQ_COMMAND'));const out=await x.bridge.webhook(headers());assert.equal(out.result.status,'ACCEPTED');assert.ok(x.store.getObject('TASK:STAGE5:SYNTHETIC:CLOUD'));assert.equal(response(x).command_id,'COMMAND:STAGE5:CLOUD:DGA:001');}finally{x.done();}});
test('STATUS is separate from receipt and uses the fixed command ID',async()=>{const x=setup();try{await x.boot();x.bridge.channel={channelId:'CHAN',channelToken:'TOKEN',resourceId:'RESOURCE'};x.drive.rename(name('COMMAND','REQ_COMMAND'));await x.bridge.webhook(headers());x.drive.rename(name('STATUS','REQ_STATUS','22345678abcdef12'));const out=await x.bridge.webhook(headers());assert.equal(out.result.operation,'STATUS');assert.equal(response(x).command_id,'COMMAND:STAGE5:CLOUD:DGA:001');}finally{x.done();}});
test('REPLAY produces no second logical task and is audited as replay',async()=>{const x=setup();try{await x.boot();x.bridge.channel={channelId:'CHAN',channelToken:'TOKEN',resourceId:'RESOURCE'};x.drive.rename(name('COMMAND','REQ_COMMAND'));await x.bridge.webhook(headers());x.drive.rename(name('REPLAY','REQ_REPLAY','32345678abcdef12'));const out=await x.bridge.webhook(headers());assert.equal(out.result.replay,true);assert.equal(x.store.getAudit().filter(a=>a.command_id==='COMMAND:STAGE5:CLOUD:DGA:001').length,1);assert.equal(response(x).replay,true);}finally{x.done();}});
test('wrong file parent, modifier, gate, invalid name and repeat nonce all fail closed',async()=>{const x=setup();try{await x.boot();x.bridge.channel={channelId:'CHAN',channelToken:'TOKEN',resourceId:'RESOURCE'};x.drive.rename(name('READ','REQ_OTHER'),{permissionId:'OTHER'});assert.equal((await x.bridge.webhook(headers())).result.result,'ACTOR_BINDING_UNPROVEN');x.drive.rename(name('READ','REQ_GATE','12345678abcdef12','22222222-2222-2222-2222-222222222222'));assert.equal((await x.bridge.webhook(headers())).result.result,'GATE_INSTANCE_MISMATCH');x.drive.rename('not-an-envelope');assert.equal((await x.bridge.webhook(headers())).result.result,'INVALID_METADATA_ENVELOPE');x.drive.rename(name('READ','REQ_NONCE','same_nonce_123'));assert.equal((await x.bridge.webhook(headers())).result.result,'PASS');x.drive.rename(name('STATUS','REQ_NONCE_2','same_nonce_123'));assert.equal((await x.bridge.webhook(headers())).result.result,'NONCE_REPLAY');x.drive.metas.get('REQ').parents=['OTHER'];assert.equal((await x.bridge.webhook(headers())).result.result,'REMOTE_READ_INVALID');}finally{x.done();}});
test('workflow configures only the explicit public staging URL before one exact deploy',()=>{const workflow=fs.readFileSync(new URL('../.github/workflows/render-stage5-cloud-gate.yml',import.meta.url),'utf8');assert.match(workflow,/GATE_COMMIT: 1ae9e99fa5723a1ecba88841a411519d19f8c889/);assert.match(workflow,/TARGET_COMMIT=os\.environ\['GATE_COMMIT'\]/);assert.match(workflow,/call\('PUT',f'\/services\/\{STAGING_ID\}\/env-vars\/STAGE5_PUBLIC_URL',\{'value':'https:\/\/cf2-stage5-role-gate\.onrender\.com'\}\)/);assert.match(workflow,/call\('GET',f'\/services\/\{STAGING_ID\}\/env-vars\/STAGE5_PUBLIC_URL'\)/);assert.match(workflow,/env_keys_after=\{row\.get\('envVar',row\)\.get\('key'\) for row in env_rows_after\}/);assert.equal((workflow.match(/call\('POST',f'\/services\/\{STAGING_ID\}\/deploys'/g)??[]).length,1);assert.doesNotMatch(workflow,/\/env-vars'\s*,|call\('PATCH'|call\('POST','\/services'|DATABASE_URL.*value/);});
test('OAuth callback remains public in Render and localhost is DEV/test only',()=>{const source=fs.readFileSync(new URL('../src/stage5-cloud-gate-server.mjs',import.meta.url),'utf8');assert.match(source,/RENDER_EXTERNAL_URL_REQUIRED/);assert.match(source,/\['development','test'\]/);});
