import test from 'node:test';
import assert from 'node:assert/strict';
import {MCP_ACTOR_ROLES,MCP_TOOLS} from '../src/remote-mcp.mjs';
import {ProductionRoleInterface} from '../src/production-role-interface.mjs';
import {commandFingerprint,replayIdempotencyResponse,storedIdempotencyResponse,validateWriterToolArgs} from '../src/writer-contract.mjs';

const stamp='2026-09-04T00:00:00.000Z';
const diego={actor_id:'ACTOR:DIEGO',allowed_roles:MCP_ACTOR_ROLES['ACTOR:DIEGO']};
const task=(id='TASK:TEST:001',state='OPEN')=>({id,type:'TASK',status:state,created_at:stamp,updated_at:stamp,basis_ref:['TEST'],action:'TEST',state,responsible_role:'DGA',related_ids:[],...(state==='DONE'?{closure_ref:'PROOF:TEST:001'}:{})});
const verification=(id='VERIFICATION:TEST:001',subject_id='TASK:TEST:001',extra={})=>({id,type:'VERIFICATION',status:'CURRENT',created_at:stamp,updated_at:stamp,basis_ref:['TEST'],subject_id,attribute:'HEALTH',value:true,class:'FIJO',verified_at:stamp,verified_by:'ACTOR:DIEGO',evidence_ref:'PROOF:TEST:001',...extra});
const create=(object=task(),extra={})=>({command_id:'COMMAND:TEST:CREATE:001',command_type:'CREATE_TASK',idempotency_key:'test-create-001',payload:{object},...extra});
const transition=(state='DONE',extra={})=>({command_id:'COMMAND:TEST:TRANSITION:001',command_type:'TRANSITION_TASK',idempotency_key:'test-transition-001',payload:{task_id:'TASK:TEST:001',state,...(state==='DONE'?{closure_ref:'PROOF:TEST:001'}:{})},...extra});
const record=(object=verification(),extra={})=>({command_id:'COMMAND:TEST:VERIFY:001',command_type:'RECORD_VERIFICATION',idempotency_key:'test-verify-001',payload:{object},...extra});

class Store{
  constructor(){this.objects=new Map();this.proofs=new Set();this.idempotency=new Map();this.writes=0;this.version=0;}
  async writer(){return'CF2_WRITER';}
  async getObject(id){return this.objects.get(id)??null;}
  async hasProof(id){return this.proofs.has(id);}
  async replayCommand(command){const stored=this.idempotency.get(command.idempotency_key);return stored?replayIdempotencyResponse(stored,commandFingerprint(command)):null;}
  async submitCommand(command){const fingerprint=commandFingerprint(command),stored=this.idempotency.get(command.idempotency_key);if(stored)return replayIdempotencyResponse(stored,fingerprint);this.writes++;const object=command.payload.object;if(command.command_type==='CREATE_TASK'||command.command_type==='RECORD_VERIFICATION')this.objects.set(object.id,object);if(command.command_type==='TRANSITION_TASK'){const old=this.objects.get(command.payload.task_id);this.objects.set(old.id,{...old,state:command.payload.state,status:command.payload.state});}const response={accepted:true,resulting_state_version:++this.version,emitted_event_ids:[`EVENT:${this.version}`]};this.idempotency.set(command.idempotency_key,storedIdempotencyResponse(response,fingerprint));return response;}
  seed(object){this.objects.set(object.id,object);return object;}
  proof(id='PROOF:TEST:001'){this.proofs.add(id);return id;}
}
const api=store=>new ProductionRoleInterface(store);
const submit=(store,command,acting_role='DGA')=>api(store).submitRoleCommand({principal:diego,acting_role,command});
const schema=name=>MCP_TOOLS.find(tool=>tool.name===name).inputSchema;

test('P0-01 submit_task_command publishes a closed discriminated schema',()=>{const value=schema('submit_task_command');assert.deepEqual(value.properties.acting_role.enum,['DGA','PRODUCTOR_MUSICAL']);assert.equal(value.properties.command.oneOf.length,2);assert.deepEqual(value.properties.command.oneOf.map(x=>x.properties.command_type.const),['CREATE_TASK','TRANSITION_TASK']);assert.equal(value.additionalProperties,false);assert.equal(value.properties.command.oneOf.every(x=>x.additionalProperties===false),true);});
test('P0-02 submit_verification publishes its complete closed schema',()=>{const value=schema('submit_verification'),command=value.properties.command;assert.deepEqual(value.properties.acting_role.enum,['DGA','PRODUCTOR_MUSICAL']);assert.equal(command.properties.command_type.const,'RECORD_VERIFICATION');assert.equal(command.additionalProperties,false);assert.deepEqual(command.properties.payload.properties.object.properties.class.enum,['FIJO','VOLÁTIL','CONDICIONAL']);});
test('P0-03 invalid acting_role is rejected',()=>assert.equal(validateWriterToolArgs('submit_task_command',{acting_role:'CLAUDIO',command:create()}),false));
test('P0-04 wrong command_type is rejected by each tool contract',()=>{assert.equal(validateWriterToolArgs('submit_task_command',{acting_role:'DGA',command:record()}),false);assert.equal(validateWriterToolArgs('submit_verification',{acting_role:'DGA',command:create()}),false);});
test('P0-05 client actor_id and actor_role are rejected',async()=>{const store=new Store();assert.equal((await submit(store,{...create(),actor_id:'ACTOR:DIEGO'})).reason_code,'ACTOR_MISMATCH');assert.equal((await submit(store,{...create(),actor_role:'DGA'})).reason_code,'ACTOR_MISMATCH');});
test('P0-06 TASK state outside the enum is rejected',async()=>{const store=new Store(),command=create({...task(),state:'REOPENED',status:'REOPENED'});assert.equal((await submit(store,command)).reason_code,'INVALID_SCHEMA');assert.equal(store.writes,0);});
test('P0-07 CREATE_TASK is insert-only',async()=>{const store=new Store();store.seed(task());assert.equal((await submit(store,create())).reason_code,'OBJECT_ALREADY_EXISTS');assert.equal(store.writes,0);});
test('P0-08 DONE cannot transition to OPEN',async()=>{const store=new Store();store.seed(task('TASK:TEST:001','DONE'));store.proof();assert.equal((await submit(store,transition('OPEN'))).reason_code,'INVALID_STATE_TRANSITION');assert.equal(store.writes,0);});
test('P0-09 CANCELLED cannot transition to OPEN',async()=>{const store=new Store();store.seed(task('TASK:TEST:001','CANCELLED'));assert.equal((await submit(store,transition('OPEN'))).reason_code,'INVALID_STATE_TRANSITION');assert.equal(store.writes,0);});
test('P0-10 DONE without closure_ref is rejected',async()=>{const store=new Store();store.seed(task());const command=transition('DONE');delete command.payload.closure_ref;assert.equal((await submit(store,command)).reason_code,'INVALID_SCHEMA');assert.equal(store.writes,0);});
test('P0-11 DONE with a missing proof is rejected',async()=>{const store=new Store();store.seed(task());assert.equal((await submit(store,transition('DONE'))).reason_code,'MISSING_CLOSURE_PROOF');assert.equal(store.writes,0);});
test('P0-12 verification evidence_ref must resolve to a proof',async()=>{const store=new Store();store.seed(task());assert.equal((await submit(store,record())).reason_code,'PROOF_NOT_FOUND');assert.equal(store.writes,0);});
test('P0-13 verification subject must exist',async()=>{const store=new Store();store.proof();assert.equal((await submit(store,record())).reason_code,'UNKNOWN_SUBJECT');assert.equal(store.writes,0);});
test('P0-14 RECORD_VERIFICATION is insert-only',async()=>{const store=new Store();store.seed(task());store.seed(verification());store.proof();assert.equal((await submit(store,record())).reason_code,'OBJECT_ALREADY_EXISTS');assert.equal(store.writes,0);});
test('P0-15 invalid verification class is rejected',async()=>{const store=new Store();assert.equal((await submit(store,record(verification(undefined,undefined,{class:'FOREVER'})))).reason_code,'INVALID_SCHEMA');assert.equal(store.writes,0);});
test('P0-16 VOLÁTIL requires a valid valid_until',async()=>{const store=new Store();assert.equal((await submit(store,record(verification(undefined,undefined,{class:'VOLÁTIL'})))).reason_code,'INVALID_SCHEMA');assert.equal(store.writes,0);});
test('P0-17 CONDICIONAL requires a non-empty invalidation_rule',async()=>{const store=new Store();assert.equal((await submit(store,record(verification(undefined,undefined,{class:'CONDICIONAL'})))).reason_code,'INVALID_SCHEMA');assert.equal(store.writes,0);});
test('P0-18 identical replay returns replay=true without another write',async()=>{const store=new Store();store.proof();const command=create(task('TASK:CANARY:NEW:001'));command.command_id='COMMAND:CANARY:CREATE:NEW:001';command.idempotency_key='canary-new-001';const first=await submit(store,command),second=await submit(store,command);assert.equal(first.accepted,true);assert.equal(second.replay,true);assert.equal(store.writes,1);});
test('P0-19 idempotency key collision with a different payload is rejected',async()=>{const store=new Store();const first=create(task('TASK:TEST:001')),changed=create(task('TASK:TEST:002'));changed.command_id=first.command_id;changed.idempotency_key=first.idempotency_key;assert.equal((await submit(store,first)).accepted,true);const collision=await submit(store,changed);assert.equal(collision.accepted,false);assert.equal(collision.reason_code,'IDEMPOTENCY_CONFLICT');assert.equal(store.writes,1);});
test('P0-20 CANARY command cannot write a non-CANARY target',async()=>{const store=new Store(),command=create(task('TASK:REAL:001'));command.command_id='COMMAND:CANARY:CREATE:001';command.idempotency_key='canary-cross-001';assert.equal((await submit(store,command)).reason_code,'CANARY_NAMESPACE_VIOLATION');assert.equal(store.writes,0);});
test('P0-21 non-CANARY command cannot write a CANARY target',async()=>{const store=new Store(),command=create(task('TASK:CANARY:NEW:001'));assert.equal((await submit(store,command)).reason_code,'CANARY_NAMESPACE_VIOLATION');assert.equal(store.writes,0);});
test('P0-22 CANARY verification cannot reference a non-CANARY subject',async()=>{const store=new Store();store.seed(task('TASK:REAL:001'));store.proof('PROOF:CANARY:NEW:001');const object=verification('VERIFICATION:CANARY:NEW:001','TASK:REAL:001',{evidence_ref:'PROOF:CANARY:NEW:001'}),command=record(object);command.command_id='COMMAND:CANARY:VERIFY:NEW:001';command.idempotency_key='canary-verify-new-001';assert.equal((await submit(store,command)).reason_code,'CANARY_NAMESPACE_VIOLATION');assert.equal(store.writes,0);});
test('P0-23 an existing subject visible to Diego is accepted',async()=>{const store=new Store();store.seed(task());store.proof();const result=await submit(store,record());assert.equal(result.accepted,true);assert.equal(store.writes,1);});
test('P0-24 legacy idempotency rows without a fingerprint fail closed',async()=>{const store=new Store(),command=create();store.idempotency.set(command.idempotency_key,{accepted:true,resulting_state_version:1});const result=await submit(store,command);assert.equal(result.accepted,false);assert.equal(result.reason_code,'IDEMPOTENCY_CONFLICT');assert.equal(store.writes,0);});
test('P0-25 identical verification replay returns replay=true without another write',async()=>{const store=new Store();store.seed(task());store.proof();const command=record(),first=await submit(store,command),second=await submit(store,command);assert.equal(first.accepted,true);assert.equal(second.replay,true);assert.equal(store.writes,1);});
