import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import { Pool } from 'pg';

const AUTHORITY = { ROLE_DELEGATED: 1, DGA_DELEGATED: 2, CLAUDIO_PERSISTED: 3, CLAUDIO_DIRECT: 4 };
const now = () => new Date().toISOString();
const json = value => JSON.stringify(value);

export class PostgresStore {
  constructor({ connectionString, ssl = { rejectUnauthorized: true } }) { if (!connectionString) throw new Error('DATABASE_URL_REQUIRED'); this.pool = new Pool({ connectionString, ssl }); }
  async close() { await this.pool.end(); }
  async migrate(dir = path.resolve(import.meta.dirname, '../migrations')) { const client = await this.pool.connect(); try { await client.query('BEGIN'); await client.query('CREATE TABLE IF NOT EXISTS schema_migrations (version TEXT PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT now())'); for (const version of (await fs.readdir(dir)).filter(name => name.endsWith('.sql')).sort()) { if ((await client.query('SELECT 1 FROM schema_migrations WHERE version=$1', [version])).rowCount) continue; await client.query(await fs.readFile(path.join(dir, version), 'utf8')); await client.query('INSERT INTO schema_migrations(version) VALUES($1)', [version]); } await client.query('COMMIT'); } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); } }
  async health() { const result = await this.pool.query("SELECT current_setting('server_version') AS postgres_version, (SELECT value FROM meta WHERE key='state_version') AS state_version"); return { database: 'UP', postgres_version: result.rows[0].postgres_version, state_version: Number(result.rows[0].state_version), outbox_pending: Number((await this.pool.query("SELECT count(*)::int AS count FROM outbox WHERE status='PENDING'")).rows[0].count) }; }
  async stateVersion(){return Number((await this.pool.query("SELECT value FROM meta WHERE key='state_version'")).rows[0].value);}
  async writer(domain){return (await this.pool.query('SELECT writer FROM cutover_domains WHERE domain=$1',[domain])).rows[0]?.writer??'UNKNOWN';}
  async getObject(id){return (await this.pool.query('SELECT body FROM objects WHERE id=$1',[id])).rows[0]?.body??null;}
  async commandStatus(command_id){const row=(await this.pool.query('SELECT result,reason,new_version,object_id FROM audit WHERE command_id=$1 ORDER BY timestamp DESC LIMIT 1',[command_id])).rows[0];return row?{command_id,status:row.result,reason_code:row.reason,state_version:Number(row.new_version),object_id:row.object_id}:{command_id,status:'UNKNOWN'};}
  async registerProof(proof_ref,body,client=this.pool){await client.query('INSERT INTO proofs(proof_ref,body,created_at) VALUES($1,$2::jsonb,$3) ON CONFLICT(proof_ref) DO NOTHING',[proof_ref,json(body),now()]);return proof_ref;}
  async submitCommand(command) { const required = ['command_id', 'command_type', 'actor_id', 'actor_role', 'issued_at', 'idempotency_key', 'payload']; if (required.some(key => !(key in command))) throw new Error('INVALID_ID'); const client = await this.pool.connect(); try { await client.query('BEGIN ISOLATION LEVEL SERIALIZABLE'); const previousResponse = await client.query('SELECT response FROM idempotency WHERE idempotency_key=$1', [command.idempotency_key]); if (previousResponse.rowCount) { await client.query('COMMIT'); return {...previousResponse.rows[0].response,replay:true}; }
      const versionRow = await client.query("SELECT value FROM meta WHERE key='state_version' FOR UPDATE"); const before = Number(versionRow.rows[0].value); if (command.expected_state_version !== undefined && command.expected_state_version !== before) throw new Error('VERSION_CONFLICT');
      let object=command.payload.object;
      if(command.command_type==='TRANSITION_TASK'){const old=(await client.query("SELECT body FROM objects WHERE id=$1 AND type='TASK' FOR UPDATE",[command.payload.task_id])).rows[0]?.body;if(!old)throw new Error('UNKNOWN_SUBJECT');object={...old,state:command.payload.state,status:command.payload.state,updated_at:now(),closure_ref:command.payload.closure_ref??null,basis_ref:[...(old.basis_ref??[]),command.command_id]};}
      if (!object?.id || !object?.type) throw new Error('INVALID_ID');
      if (object.type === 'TASK' && object.state === 'DONE') {if(!object.closure_ref)throw new Error('MISSING_CLOSURE_PROOF');if(!(await client.query('SELECT 1 FROM proofs WHERE proof_ref=$1',[object.closure_ref])).rowCount)throw new Error('MISSING_CLOSURE_PROOF');}
      if (object.type === 'DECISION') await this.#recordDecision(client, object);
      await client.query('INSERT INTO objects(id,type,status,body,created_at,updated_at) VALUES($1,$2,$3,$4::jsonb,$5,$6) ON CONFLICT(id) DO UPDATE SET status=EXCLUDED.status, body=EXCLUDED.body, updated_at=EXCLUDED.updated_at', [object.id, object.type, object.status, json(object), object.created_at, object.updated_at]);
      if (object.type === 'TASK') await client.query('INSERT INTO tasks(object_id,state,closure_ref) VALUES($1,$2,$3) ON CONFLICT(object_id) DO UPDATE SET state=EXCLUDED.state, closure_ref=EXCLUDED.closure_ref', [object.id, object.state, object.closure_ref ?? null]);
      if (object.type === 'VERIFICATION') await client.query('INSERT INTO verifications(object_id,subject_id,attribute,class,status,valid_until,invalidation_rule) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(object_id) DO UPDATE SET subject_id=EXCLUDED.subject_id,attribute=EXCLUDED.attribute,class=EXCLUDED.class,status=EXCLUDED.status,valid_until=EXCLUDED.valid_until,invalidation_rule=EXCLUDED.invalidation_rule',[object.id,object.subject_id,object.attribute,object.class,object.status,object.valid_until??null,object.invalidation_rule??null]);
      const next = before + 1; const event = { event_id: `EVENT:${crypto.randomUUID()}`, event_type: 'ACCEPTED', subject_id: object.id, occurred_at: now(), producer: 'CORE_PROD', causation_id: command.command_id, state_version: next, dedupe_key: command.idempotency_key };
      await client.query("UPDATE meta SET value=$1::jsonb WHERE key='state_version'", [json(next)]); await client.query('INSERT INTO outbox(event_id,event_type,state_version,payload,created_at,status) VALUES($1,$2,$3,$4::jsonb,$5,$6)', [event.event_id, event.event_type, next, json(event), event.occurred_at, 'PENDING']); await client.query('INSERT INTO audit(mutation_id,timestamp,actor_id,actor_role,command_id,object_id,previous_version,new_version,reason,result,authority_ref,evidence_ref) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)', [`MUTATION:${crypto.randomUUID()}`, now(), command.actor_id, command.actor_role, command.command_id, object.id, before, next, 'ACCEPTED', 'ACCEPTED',command.authority_ref??null,command.evidence_ref??object.evidence_ref??null]); const response = { accepted: true, resulting_state_version: next, emitted_event_ids: [event.event_id] }; await client.query('INSERT INTO idempotency(idempotency_key,response) VALUES($1,$2::jsonb)', [command.idempotency_key, json(response)]); await client.query('COMMIT'); return response;
    } catch (error) { await client.query('ROLLBACK'); return { accepted: false, reason_code: ['VERSION_CONFLICT','MISSING_CLOSURE_PROOF','UNKNOWN_SUBJECT'].includes(error.message)?error.message:'FAIL_CLOSED' }; } finally { client.release(); } }
  async #recordDecision(client, object) { if (!(object.authority in AUTHORITY)) throw new Error('AUTHORITY_DENIED'); const current = await client.query("SELECT object_id,authority_rank FROM decisions WHERE subject_id=$1 AND decision_key=$2 AND status='CURRENT' FOR UPDATE", [object.subject_id, object.decision_key]); if (current.rowCount) { if (AUTHORITY[object.authority] < current.rows[0].authority_rank || object.supersedes !== current.rows[0].object_id) throw new Error('CONFLICT'); await client.query("UPDATE decisions SET status='SUPERSEDED' WHERE object_id=$1", [current.rows[0].object_id]); await client.query("UPDATE objects SET status='SUPERSEDED', updated_at=$2 WHERE id=$1", [current.rows[0].object_id, now()]); } object.status = 'CURRENT'; await client.query('INSERT INTO decisions(object_id,subject_id,decision_key,status,authority,authority_rank,effective_at,supersedes) VALUES($1,$2,$3,$4,$5,$6,$7,$8)', [object.id, object.subject_id, object.decision_key, object.status, object.authority, AUTHORITY[object.authority], object.effective_at, object.supersedes ?? null]); }
}
