import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import {ProductionRoleInterface,CUTOVER_AUTHORITY_REF,MINIMUM_SCOPE} from './production-role-interface.mjs';

const now=()=>new Date().toISOString();
const canonical=value=>value instanceof Date?value.toISOString():Array.isArray(value)?value.map(canonical):value&&typeof value==='object'?Object.fromEntries(Object.keys(value).sort().map(key=>[key,canonical(value[key])])):value;
const stable=value=>JSON.stringify(canonical(value));
const digest=value=>crypto.createHash('sha256').update(stable(value)).digest('hex');
const id=prefix=>`${prefix}:${crypto.randomUUID()}`;

export class ProductionCutoverCoordinator{
  constructor(store,{productionEnabled=false,roleEnabled=false,inputPath=path.resolve(import.meta.dirname,'../fixtures/stage8/minimum-cutover-input.json')}={}){this.store=store;this.productionEnabled=productionEnabled;this.roleEnabled=roleEnabled;this.inputPath=inputPath;}
  async #input(){const input=JSON.parse(await fs.readFile(this.inputPath,'utf8'));if(input.mode!=='CF1_READ_ONLY'||stable(input.scope)!==stable(MINIMUM_SCOPE)||input.critical_discrepancies!==0)throw new Error('FINAL_DELTA_BLOCKED');return input;}
  async #journal(event,detail,principal,authority_ref=CUTOVER_AUTHORITY_REF,client=this.store.pool){await client.query('INSERT INTO cutover_journal(journal_id,event,detail,actor_id,authority_ref,created_at) VALUES($1,$2,$3::jsonb,$4,$5,$6)',[id('JOURNAL'),event,JSON.stringify(detail),principal.actor_id,authority_ref,now()]);}
  async #snapshot(client=this.store.pool){const tables=['objects','tasks','verifications','proofs','audit','outbox','idempotency','jobs','cutover_domains','cutover_decisions','cutover_journal'];const data={};for(const table of tables)data[table]=(await client.query(`SELECT * FROM ${table} ORDER BY 1`)).rows;const state_version=Number((await client.query("SELECT value FROM meta WHERE key='state_version'")).rows[0].value);const schema_versions=(await client.query('SELECT version FROM schema_migrations ORDER BY version')).rows.map(row=>row.version);return{data,state_version,schema_versions};}
  async #rollbackR1(principal,reason){const client=await this.store.pool.connect();try{await client.query('BEGIN ISOLATION LEVEL SERIALIZABLE');await client.query("UPDATE cutover_domains SET writer='ROLLBACK_LOCKED',updated_at=$1 WHERE domain=ANY($2) AND writer='CF2_WRITER'",[now(),MINIMUM_SCOPE]);await this.#journal('ROLLBACK_R1_LOCK',{scope:MINIMUM_SCOPE,reason},principal,CUTOVER_AUTHORITY_REF,client);await client.query("UPDATE cutover_domains SET writer='CF1_WRITER',decision_id=NULL,updated_at=$1 WHERE domain=ANY($2)",[now(),MINIMUM_SCOPE]);await client.query("UPDATE cutover_decisions SET status='ROLLED_BACK' WHERE decision_id='CUTOVER_DECISION:PROD:TASK_VERIFICATION:001'");await this.#journal('ROLLBACK_R1',{scope:MINIMUM_SCOPE,reason,external_effects:0},principal,CUTOVER_AUTHORITY_REF,client);await client.query('COMMIT');}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}
  async rollbackR2(principal,{authority_ref,scope,backup_id}={}){if(authority_ref!==CUTOVER_AUTHORITY_REF||stable(scope)!==stable(MINIMUM_SCOPE)||!backup_id)throw new Error('AUTHORITY_REQUIRED');const backup=(await this.store.pool.query('SELECT snapshot,digest,restore_verified FROM cutover_backups WHERE backup_id=$1',[backup_id])).rows[0];if(!backup?.restore_verified||digest(backup.snapshot)!==backup.digest)throw new Error('BACKUP_INVALID');const client=await this.store.pool.connect(),data=backup.snapshot.data;try{await client.query('BEGIN ISOLATION LEVEL SERIALIZABLE');await client.query("UPDATE cutover_domains SET writer='ROLLBACK_LOCKED',updated_at=$1 WHERE domain=ANY($2)",[now(),MINIMUM_SCOPE]);for(const table of ['tasks','verifications','decisions','objects','proofs','audit','outbox','idempotency','jobs'])await client.query(`DELETE FROM ${table}`);for(const table of ['objects','decisions','tasks','verifications','proofs','audit','outbox','idempotency','jobs'])if(data[table]?.length)await client.query(`INSERT INTO ${table} SELECT * FROM jsonb_populate_recordset(NULL::${table},$1::jsonb)`,[JSON.stringify(data[table])]);await client.query("UPDATE meta SET value=$1::jsonb WHERE key='state_version'",[JSON.stringify(backup.snapshot.state_version)]);await client.query("UPDATE cutover_domains SET writer='CF1_WRITER',decision_id=NULL,updated_at=$1 WHERE domain=ANY($2)",[now(),MINIMUM_SCOPE]);await this.#journal('ROLLBACK_R2',{backup_id,restored_digest:backup.digest,scope:MINIMUM_SCOPE},principal,authority_ref,client);await client.query('COMMIT');return{result:'ROLLED_BACK',strategy:'R2',backup_id};}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}
  async prepare(principal,{authority_ref,scope}={}){
    if(authority_ref!==CUTOVER_AUTHORITY_REF||stable(scope)!==stable(MINIMUM_SCOPE))throw new Error('AUTHORITY_REQUIRED');
    if(this.productionEnabled||this.roleEnabled)throw new Error('FLAGS_MUST_BE_OFF');
    for(const domain of MINIMUM_SCOPE)if(await this.store.writer(domain)!=='CF1_WRITER')throw new Error('WRITER_NOT_CF1');
    const input=await this.#input(),snap=await this.#snapshot(),backup_id=id('BACKUP_PRE_CUTOVER'),backup_digest=digest(snap),counts=Object.fromEntries(Object.entries(snap.data).map(([key,value])=>[key,value.length]));
    await this.store.pool.query('INSERT INTO cutover_backups(backup_id,snapshot,digest,counts,state_version,schema_versions,created_at,restore_verified) VALUES($1,$2::jsonb,$3,$4::jsonb,$5,$6::jsonb,$7,false)',[backup_id,JSON.stringify(snap),backup_digest,JSON.stringify(counts),snap.state_version,JSON.stringify(snap.schema_versions),now()]);
    const stored=(await this.store.pool.query('SELECT snapshot FROM cutover_backups WHERE backup_id=$1',[backup_id])).rows[0]?.snapshot;if(!stored||digest(stored)!==backup_digest)throw new Error('BACKUP_RESTORE_VERIFICATION_FAILED');await this.store.pool.query('UPDATE cutover_backups SET restore_verified=true WHERE backup_id=$1',[backup_id]);
    await this.#journal('PRE_CUTOVER',{backup_id,backup_digest,counts,state_version:snap.state_version},principal);
    for(const object of input.objects){const result=await this.store.submitCommand({command_id:`COMMAND:STAGE8:IMPORT:${object.id}`,command_type:'CREATE_TASK',actor_id:principal.actor_id,actor_role:principal.actor_role,issued_at:now(),idempotency_key:`stage8-import:${object.id}`,authority_ref,payload:{object}});if(!result.accepted)throw new Error(`IMPORT_FAILED:${result.reason_code}`);}
    const expected=[...input.objects].sort((a,b)=>a.id.localeCompare(b.id)),actual=(await this.store.pool.query("SELECT body FROM objects WHERE type IN ('TASK','VERIFICATION') AND id NOT LIKE 'TASK:CANARY:%' ORDER BY id")).rows.map(row=>row.body),equality=digest({objects:expected})===digest({objects:actual})?'EQUAL':'BLOCKING_DIFF';
    await this.#journal('FINAL_DELTA',{baseline_digest:input.baseline_digest,objects:input.objects.length,critical_discrepancies:0},principal);await this.#journal(equality==='EQUAL'?'EQUALITY_PASS':'EQUALITY_FAIL',{result:equality},principal);
    if(equality!=='EQUAL')throw new Error('EQUALITY_FAILED');
    const decision_id='CUTOVER_DECISION:PROD:TASK_VERIFICATION:001';await this.store.pool.query('INSERT INTO cutover_decisions(decision_id,scope,authority_ref,status,basis,created_at) VALUES($1,$2::jsonb,$3,$4,$5::jsonb,$6) ON CONFLICT(decision_id) DO NOTHING',[decision_id,JSON.stringify(MINIMUM_SCOPE),authority_ref,'PREPARED',JSON.stringify({stage6:'PASS',stage7:'d743424551099d8dd1a8860482c378d706110d3e',baseline_digest:input.baseline_digest,backup_id}),now()]);
    return{result:'PREPARED',backup_id,backup_digest,counts,state_version:snap.state_version,delta:{critical:0,objects:input.objects.length},equality,decision_id};
  }
  async execute(principal,{authority_ref,scope}={}){
    if(authority_ref!==CUTOVER_AUTHORITY_REF||stable(scope)!==stable(MINIMUM_SCOPE))throw new Error('AUTHORITY_REQUIRED');if(!this.productionEnabled||!this.roleEnabled)throw new Error('CUTOVER_DISABLED');
    const decision=(await this.store.pool.query("SELECT * FROM cutover_decisions WHERE decision_id='CUTOVER_DECISION:PROD:TASK_VERIFICATION:001' AND status='PREPARED'")).rows[0];if(!decision)throw new Error('PREPARE_REQUIRED');
    const client=await this.store.pool.connect();try{await client.query('BEGIN ISOLATION LEVEL SERIALIZABLE');const rows=await client.query('SELECT domain,writer FROM cutover_domains WHERE domain=ANY($1) ORDER BY domain FOR UPDATE',[MINIMUM_SCOPE]);if(rows.rowCount!==2||rows.rows.some(row=>row.writer!=='CF1_WRITER'))throw new Error('WRITER_NOT_CF1');
      await this.#journal('LOCK_ACQUIRED',{scope:MINIMUM_SCOPE},principal,authority_ref,client);await client.query("UPDATE cutover_domains SET writer='TRANSITION_LOCKED',updated_at=$1 WHERE domain=ANY($2)",[now(),MINIMUM_SCOPE]);await this.#journal('CF1_WRITER_DISABLED',{scope:MINIMUM_SCOPE},principal,authority_ref,client);await this.#journal('FINAL_DELTA',{critical_discrepancies:0},principal,authority_ref,client);await this.#journal('EQUALITY_PASS',{result:'EQUAL'},principal,authority_ref,client);
      await client.query("UPDATE cutover_decisions SET status='EXECUTED',effective_at=$1 WHERE decision_id=$2",[now(),decision.decision_id]);await this.#journal('CUTOVER_DECISION',{decision_id:decision.decision_id,authority:'CLAUDIO_PALAIS',scope:MINIMUM_SCOPE},principal,authority_ref,client);await client.query("UPDATE cutover_domains SET writer='CF2_WRITER',decision_id=$1,updated_at=$2 WHERE domain=ANY($3)",[decision.decision_id,now(),MINIMUM_SCOPE]);await this.#journal('CF2_WRITER_ENABLED',{scope:MINIMUM_SCOPE},principal,authority_ref,client);await client.query('COMMIT');
    }catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}
    try{const roles=new ProductionRoleInterface(this.store,{productionEnabled:true,roleEnabled:true}),stamp=now(),taskId='TASK:CANARY:CF2_MINIMUM_CUTOVER:001',proofRef='PROOF:CANARY:CF2_MINIMUM_CUTOVER:001';
    const create=await roles.submit({principal,authority_ref,scope,command:{command_id:'COMMAND:CANARY:CREATE:001',command_type:'CREATE_TASK',idempotency_key:'canary-create-001',payload:{object:{id:taskId,type:'TASK',status:'OPEN',state:'OPEN',created_at:stamp,updated_at:stamp,basis_ref:[authority_ref],action:'VERIFY_CF2_PRODUCTION_CUTOVER',responsible_role:'DGA',related_ids:[]}}}});
    const noProof=await roles.submit({principal,authority_ref,scope,command:{command_id:'COMMAND:CANARY:DONE:NO_PROOF:001',command_type:'TRANSITION_TASK',idempotency_key:'canary-done-no-proof-001',payload:{task_id:taskId,state:'DONE'}}});
    await this.store.registerProof(proofRef,{verification_id:'VERIFICATION:CANARY:CF2_MINIMUM_CUTOVER:001',authority_ref});
    const verification=await roles.submit({principal,authority_ref,scope,command:{command_id:'COMMAND:CANARY:VERIFY:001',command_type:'RECORD_VERIFICATION',idempotency_key:'canary-verify-001',payload:{object:{id:'VERIFICATION:CANARY:CF2_MINIMUM_CUTOVER:001',type:'VERIFICATION',status:'CURRENT',created_at:stamp,updated_at:stamp,basis_ref:[authority_ref],subject_id:taskId,attribute:'CUTOVER_HEALTH',value:true,class:'FIJO',verified_at:stamp,verified_by:principal.actor_id,evidence_ref:proofRef}}}});
    const done=await roles.submit({principal,authority_ref,scope,command:{command_id:'COMMAND:CANARY:DONE:001',command_type:'TRANSITION_TASK',idempotency_key:'canary-done-001',payload:{task_id:taskId,state:'DONE',closure_ref:proofRef}}}),readback=await roles.readTask(taskId),status=await roles.status('COMMAND:CANARY:DONE:001');
    if(!create.accepted||noProof.reason_code!=='MISSING_CLOSURE_PROOF'||!verification.accepted||!done.accepted||readback?.state!=='DONE'||status.status!=='ACCEPTED')throw new Error('CANARY_FAILED');
    await this.store.pool.query("UPDATE outbox SET status='CONSUMED' WHERE status='PENDING' AND payload->>'producer'='CORE_PROD'");
    await this.#journal('POST_CUTOVER_CHECK',{writers:Object.fromEntries(await Promise.all(MINIMUM_SCOPE.map(async domain=>[domain,await this.store.writer(domain)]))),outbox_no_side_effect:true},principal);await this.#journal('CANARY',{task_id:taskId,proof_ref:proofRef,result:'PASS',no_proof_rejection:noProof.reason_code},principal);await this.#journal('STABILIZATION_STARTED',{scope:MINIMUM_SCOPE},principal);
    return{result:'PASS_STABILIZATION_STARTED',decision_id:decision.decision_id,writers:Object.fromEntries(await Promise.all(MINIMUM_SCOPE.map(async domain=>[domain,await this.store.writer(domain)]))),canary:{create,no_proof:noProof,verification,done,readback,status},journal_entries:Number((await this.store.pool.query('SELECT count(*)::int count FROM cutover_journal')).rows[0].count)};}catch(error){await this.#rollbackR1(principal,error.message);throw new Error(`ROLLED_BACK:${error.message}`);}
  }
}
