import {orchestrationTools} from './orchestration-api.mjs';
import {strict} from './actor-transport.mjs';
import crypto from 'node:crypto';
import {validateWriterToolArgs,writerSchemasForRoles} from './writer-contract.mjs';

export const MCP_PROTOCOL_VERSION='2025-06-18';
export const MCP_SCOPE='cf2:mcp';
export const MCP_ACTOR_ROLES=Object.freeze({
  'ACTOR:DIEGO':Object.freeze(['DGA','PRODUCTOR_MUSICAL']),
  'ACTOR:GABY_CHAT':Object.freeze(['GABY_CHAT']),
  'ACTOR:GABY_CW':Object.freeze(['GABY_CW_AUDIOVISUAL','GABY_CW_DOCUMENTAL']),
  'ACTOR:CODEX':Object.freeze(['CODEX']),
  'ACTOR:CLAUDE_CODE':Object.freeze(['CLAUDE_CODE'])
});

const RESOURCE_ACTORS=Object.freeze({
  '/mcp/diego':'ACTOR:DIEGO',
  '/mcp/gaby-chat':'ACTOR:GABY_CHAT',
  '/mcp/gaby-cw':'ACTOR:GABY_CW',
  '/mcp/codex':'ACTOR:CODEX',
  '/mcp/claude-code':'ACTOR:CLAUDE_CODE'
});
const ACCESS_TTL_MS=3_600_000,REFRESH_TTL_MS=2_592_000_000,CODE_TTL_MS=300_000;
const digest=value=>crypto.createHash('sha256').update(value).digest('hex');
const randomToken=()=>crypto.randomBytes(32).toString('base64url');
const mcpJson=(response,status,value,headers={})=>response.writeHead(status,{'content-type':'application/json','cache-control':'no-store',...headers}).end(JSON.stringify(value));
const rpcResult=(id,result)=>({jsonrpc:'2.0',id,result});
const rpcError=(id,code,message,data)=>({jsonrpc:'2.0',id:id??null,error:{code,message,...(data?{data}:{})}});
const toolResult=value=>({content:[{type:'text',text:JSON.stringify(value)}],structuredContent:value,isError:false});
const toolFailure=(error_code,detail={})=>({content:[{type:'text',text:JSON.stringify({result:'FAIL_CLOSED',error_code,...detail})}],structuredContent:{result:'FAIL_CLOSED',error_code,...detail},isError:true});

export const resourceActor=(baseUrl,resource)=>{
  let parsed;try{parsed=new URL(resource);}catch{return null;}
  if(parsed.origin!==new URL(baseUrl).origin||parsed.search||parsed.hash)return null;
  return RESOURCE_ACTORS[parsed.pathname]??null;
};
export const validRedirectUri=value=>{try{const uri=new URL(value),transport=uri.protocol==='https:'||(uri.protocol==='http:'&&['127.0.0.1','localhost','[::1]'].includes(uri.hostname));return transport&&!uri.hash&&!uri.username&&!uri.password;}catch{return false;}};

const workflowCommands=Object.freeze({START_WORKFLOW:'start_workflow',CONTROL_WORKFLOW:'control_workflow'});
const executorThreadTools=Object.freeze(new Set(['read_inbox','read_thread','reply_to_message','get_thread_status']));
export function mcpToolsFor(principal,{orchestration=false}={}){
  const schemas=writerSchemasForRoles(principal?.allowed_roles);
  const diegoOrchestration=orchestration&&principal?.actor_id==='ACTOR:DIEGO';
  const executorOrchestration=orchestration&&['ACTOR:GABY_CHAT','ACTOR:GABY_CW'].includes(principal?.actor_id);
  const taskSchema=structuredClone(schemas.submit_task_command);
  if(diegoOrchestration)for(const [command_type,name] of Object.entries(workflowCommands))taskSchema.properties.command.oneOf.push({type:'object',additionalProperties:false,required:['command_type','payload'],properties:{command_type:{const:command_type},payload:orchestrationTools.find(tool=>tool.name===name).inputSchema}});
  const tools=[
    Object.freeze({name:'get_my_tasks',description:'Read tasks visible to the authenticated CF2 principal.',inputSchema:{type:'object',properties:{limit:{type:'integer',minimum:1,maximum:100}},additionalProperties:false}}),
    Object.freeze({name:'get_task',description:'Read one task by its stable CF2 ID. A THREAD: ID returns its authorized workflow, automatic actor responses and audit trail.',inputSchema:{type:'object',properties:{task_id:{type:'string',minLength:1,maxLength:200}},required:['task_id'],additionalProperties:false}}),
    Object.freeze({name:'submit_task_command',description:'Submit a TASK command through the server-side CF2 RoleInterface. actor_id, actor_role, and issued_at are bound server-side.'+(diegoOrchestration?' Diego DGA can also submit START_WORKFLOW or CONTROL_WORKFLOW with payload equal to the corresponding public tool arguments. Use START_WORKFLOW for actor assignments, never cross-role CREATE_TASK. Read returns with get_task using the returned THREAD: ID.':''),inputSchema:taskSchema}),
    ...(['ACTOR:CODEX','ACTOR:CLAUDE_CODE'].includes(principal?.actor_id)?[]:[Object.freeze({name:'submit_verification',description:'Submit a VERIFICATION through the server-side CF2 RoleInterface. actor_id, actor_role, issued_at, and verified_by are bound server-side.',inputSchema:schemas.submit_verification})]),
    Object.freeze({name:'get_status',description:'Read the status of a submitted CF2 command.',inputSchema:{type:'object',properties:{command_id:{type:'string',minLength:1,maxLength:200}},required:['command_id'],additionalProperties:false}})
  ];
  const publishedOrchestration=diegoOrchestration?orchestrationTools:(executorOrchestration?orchestrationTools.filter(tool=>executorThreadTools.has(tool.name)):[]);
  return Object.freeze([...tools,...publishedOrchestration]);
}

export class RemoteMcpServer{
  constructor(store,{baseUrl,roleInterface,orchestration=null,clock=()=>Date.now()}={}){if(!store?.pool||!baseUrl||!roleInterface)throw new Error('REMOTE_MCP_CONFIGURATION_REQUIRED');this.store=store;this.baseUrl=baseUrl;this.roleInterface=roleInterface;this.orchestration=orchestration;this.clock=clock;this.registrationWindow=new Map();}
  resource(pathname){return `${this.baseUrl}${pathname}`;}
  health(){return{status:'READY',protocol:MCP_PROTOCOL_VERSION,oauth:'READY',resources:Object.keys(RESOURCE_ACTORS).map(path=>this.resource(path))};}
  protectedMetadata(resource){const actor=resourceActor(this.baseUrl,resource);if(!actor)return null;return{resource,authorization_servers:[this.baseUrl],scopes_supported:[MCP_SCOPE],bearer_methods_supported:['header']};}
  authorizationMetadata(){return{issuer:this.baseUrl,authorization_endpoint:`${this.baseUrl}/oauth/mcp/authorize`,token_endpoint:`${this.baseUrl}/oauth/mcp/token`,registration_endpoint:`${this.baseUrl}/oauth/mcp/register`,revocation_endpoint:`${this.baseUrl}/oauth/mcp/revoke`,scopes_supported:[MCP_SCOPE],response_types_supported:['code'],grant_types_supported:['authorization_code','refresh_token'],code_challenge_methods_supported:['S256'],token_endpoint_auth_methods_supported:['none']};}
  #originAllowed(request){const origin=request.headers.origin;if(!origin)return true;try{return new URL(origin).origin===new URL(this.baseUrl).origin;}catch{return false;}}
  #registrationAllowed(request){const key=request.socket?.remoteAddress??'unknown',now=this.clock(),recent=(this.registrationWindow.get(key)??[]).filter(value=>value>now-3_600_000);if(recent.length>=20)return false;recent.push(now);this.registrationWindow.set(key,recent);return true;}
  async register(body,request){if(!this.#registrationAllowed(request))throw new Error('REGISTRATION_RATE_LIMITED');const uris=body?.redirect_uris;if(!Array.isArray(uris)||uris.length<1||uris.length>8||uris.some(uri=>typeof uri!=='string'||uri.length>2048||!validRedirectUri(uri)))throw new Error('INVALID_REDIRECT_URI');if(body.token_endpoint_auth_method&&body.token_endpoint_auth_method!=='none')throw new Error('CONFIDENTIAL_CLIENT_REJECTED');const client_id=`MCP_CLIENT:${crypto.randomUUID()}`,client_name=typeof body.client_name==='string'&&body.client_name.trim()?body.client_name.trim().slice(0,120):'MCP Client';await this.store.pool.query('INSERT INTO mcp_oauth_clients(client_id,client_name,redirect_uris,created_at) VALUES($1,$2,$3::jsonb,now())',[client_id,client_name,JSON.stringify(uris)]);return{client_id,client_id_issued_at:Math.floor(this.clock()/1000),client_name,redirect_uris:uris,grant_types:['authorization_code','refresh_token'],response_types:['code'],token_endpoint_auth_method:'none'};}
  async authorizationRequest(url){const client_id=url.searchParams.get('client_id'),redirect_uri=url.searchParams.get('redirect_uri'),resource=url.searchParams.get('resource'),state=url.searchParams.get('state'),challenge=url.searchParams.get('code_challenge'),scope=url.searchParams.get('scope');if(url.searchParams.get('response_type')!=='code'||url.searchParams.get('code_challenge_method')!=='S256'||!client_id||!redirect_uri||!resource||!state||state.length>512||(scope&&scope!==MCP_SCOPE)||!/^[A-Za-z0-9_-]{43,128}$/.test(challenge??'')||!resourceActor(this.baseUrl,resource))throw new Error('OAUTH_REQUEST_INVALID');const client=(await this.store.pool.query('SELECT redirect_uris FROM mcp_oauth_clients WHERE client_id=$1',[client_id])).rows[0];if(!client||!client.redirect_uris.includes(redirect_uri))throw new Error('OAUTH_CLIENT_INVALID');return{client_id,redirect_uri,resource,state,code_challenge:challenge};}
  async resolveActor({resource,human_fingerprint,directPrincipal}){const actor_id=resourceActor(this.baseUrl,resource);if(!actor_id)throw new Error('MCP_RESOURCE_INVALID');if(actor_id==='ACTOR:DIEGO'){if(directPrincipal?.actor_id!==actor_id)throw new Error('MCP_PRINCIPAL_REJECTED');return actor_id;}const row=(await this.store.pool.query("SELECT actor_id FROM role_gateway_enrollments WHERE actor_id=$1 AND status='CONSUMED' AND human_fingerprint=$2",[actor_id,human_fingerprint])).rows[0];if(row?.actor_id!==actor_id)throw new Error('MCP_PRINCIPAL_REJECTED');return actor_id;}
  async completeAuthorization({request,actor_id}){const code=randomToken();await this.store.pool.query('INSERT INTO mcp_oauth_codes(code_hash,client_id,redirect_uri,resource,actor_id,code_challenge,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7)',[digest(code),request.client_id,request.redirect_uri,request.resource,actor_id,request.code_challenge,new Date(this.clock()+CODE_TTL_MS)]);const target=new URL(request.redirect_uri);target.searchParams.set('code',code);target.searchParams.set('state',request.state);target.searchParams.set('iss',this.baseUrl);return target.toString();}
  async #authorizationCodeToken(form){const code=form.get('code'),client_id=form.get('client_id'),redirect_uri=form.get('redirect_uri'),resource=form.get('resource'),verifier=form.get('code_verifier');if(!code||!client_id||!redirect_uri||!resource||!/^[A-Za-z0-9._~-]{43,128}$/.test(verifier??''))throw new Error('TOKEN_REQUEST_INVALID');const client=await this.store.pool.connect();try{await client.query('BEGIN');const row=(await client.query('SELECT * FROM mcp_oauth_codes WHERE code_hash=$1 FOR UPDATE',[digest(code)])).rows[0],challenge=crypto.createHash('sha256').update(verifier).digest('base64url');if(!row||row.consumed_at||new Date(row.expires_at).getTime()<=this.clock()||row.client_id!==client_id||row.redirect_uri!==redirect_uri||row.resource!==resource||row.code_challenge!==challenge)throw new Error('TOKEN_REQUEST_INVALID');await client.query('UPDATE mcp_oauth_codes SET consumed_at=now() WHERE code_hash=$1',[digest(code)]);const result=await this.#createSession(client,row);await client.query('COMMIT');return result;}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}
  async #createSession(client,{client_id,actor_id,resource}){const access_token=randomToken(),refresh_token=randomToken(),session_id=`MCP_SESSION:${crypto.randomUUID()}`,now=this.clock();await client.query('INSERT INTO mcp_oauth_sessions(session_id,client_id,actor_id,resource,access_token_hash,refresh_token_hash,created_at,access_expires_at,refresh_expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[session_id,client_id,actor_id,resource,digest(access_token),digest(refresh_token),new Date(now),new Date(now+ACCESS_TTL_MS),new Date(now+REFRESH_TTL_MS)]);return{access_token,token_type:'Bearer',expires_in:ACCESS_TTL_MS/1000,refresh_token,scope:MCP_SCOPE};}
  async #refreshToken(form){const refresh_token=form.get('refresh_token'),client_id=form.get('client_id'),resource=form.get('resource');if(!refresh_token||!client_id||!resource)throw new Error('TOKEN_REQUEST_INVALID');const client=await this.store.pool.connect();try{await client.query('BEGIN');const row=(await client.query('SELECT * FROM mcp_oauth_sessions WHERE refresh_token_hash=$1 FOR UPDATE',[digest(refresh_token)])).rows[0];if(!row||row.revoked_at||new Date(row.refresh_expires_at).getTime()<=this.clock()||row.client_id!==client_id||row.resource!==resource)throw new Error('TOKEN_REQUEST_INVALID');const access_token=randomToken(),next_refresh=randomToken(),now=this.clock();await client.query('UPDATE mcp_oauth_sessions SET access_token_hash=$2,refresh_token_hash=$3,access_expires_at=$4 WHERE session_id=$1',[row.session_id,digest(access_token),digest(next_refresh),new Date(now+ACCESS_TTL_MS)]);await client.query('COMMIT');return{access_token,token_type:'Bearer',expires_in:ACCESS_TTL_MS/1000,refresh_token:next_refresh,scope:MCP_SCOPE};}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}
  async token(form){const grant=form.get('grant_type');if(grant==='authorization_code')return this.#authorizationCodeToken(form);if(grant==='refresh_token')return this.#refreshToken(form);throw new Error('UNSUPPORTED_GRANT_TYPE');}
  async revoke(form){const token=form.get('token');if(token)await this.store.pool.query('UPDATE mcp_oauth_sessions SET revoked_at=now() WHERE access_token_hash=$1 OR refresh_token_hash=$1',[digest(token)]);return{};}
  async authenticate(request,resource){const authorization=request.headers.authorization??'';if(!authorization.startsWith('Bearer '))return null;const row=(await this.store.pool.query('SELECT actor_id FROM mcp_oauth_sessions WHERE access_token_hash=$1 AND resource=$2 AND revoked_at IS NULL AND access_expires_at>now()',[digest(authorization.slice(7)),resource])).rows[0];return row?{actor_id:row.actor_id,allowed_roles:MCP_ACTOR_ROLES[row.actor_id]}:null;}
  #challenge(response,resource){const metadata=`${this.baseUrl}/.well-known/oauth-protected-resource${new URL(resource).pathname}`;return mcpJson(response,401,{error:'invalid_token'},{'www-authenticate':`Bearer resource_metadata="${metadata}", scope="${MCP_SCOPE}"`});}
  async workflowCommand(principal,args){
    strict(args,['acting_role','command']);strict(args.command,['command_type','payload']);
    if(principal.actor_id!=='ACTOR:DIEGO'||args.acting_role!=='DGA'||!principal.allowed_roles.includes('DGA'))throw new Error('ROLE_FORBIDDEN');
    const operation=workflowCommands[args.command.command_type];
    if(!this.orchestration||!operation)throw new Error('METHOD_NOT_FOUND');
    const workflow=await this.orchestration.call(principal,operation,args.command.payload);
    return{accepted:true,operation,actor_id:principal.actor_id,thread_id:workflow.thread_id,workflow};
  }
  async #getMyTasks(principal,args){const limit=Math.min(Math.max(Number(args.limit??50),1),100),roles=principal.allowed_roles;const rows=principal.actor_id==='ACTOR:DIEGO'?(await this.store.pool.query("SELECT body FROM objects WHERE type='TASK' ORDER BY updated_at DESC LIMIT $1",[limit])).rows:(await this.store.pool.query("SELECT body FROM objects WHERE type='TASK' AND body->>'responsible_role'=ANY($1::text[]) ORDER BY updated_at DESC LIMIT $2",[roles,limit])).rows;return{result:'PASS',actor_id:principal.actor_id,tasks:rows.map(row=>row.body)};}
  async #getTask(principal,args){strict(args,['task_id']);if(typeof args.task_id!=='string'||args.task_id.length>200)throw new Error('INVALID_SCHEMA');if(this.orchestration&&args.task_id.startsWith('THREAD:'))return{result:'PASS',workflow:await this.orchestration.call(principal,'read_thread',{thread_id:args.task_id})};const object=await this.store.getObject(args.task_id);if(!object||object.type!=='TASK')return{result:'UNKNOWN',task_id:args.task_id};if(principal.actor_id!=='ACTOR:DIEGO'&&!principal.allowed_roles.includes(object.responsible_role))throw new Error('ROLE_FORBIDDEN');return{result:'PASS',task:object};}
  async #callTool(principal,name,args){if(name==='submit_task_command'&&Object.hasOwn(workflowCommands,args?.command?.command_type))return this.workflowCommand(principal,args);if(this.orchestration&&orchestrationTools.some(t=>t.name===name))return this.orchestration.call(principal,name,args);if(name==='get_my_tasks')return this.#getMyTasks(principal,args);if(name==='get_task')return this.#getTask(principal,args);if(name==='get_status'){if(typeof args.command_id!=='string')throw new Error('INVALID_SCHEMA');return{result:'PASS',...(await this.store.commandStatus(args.command_id))};}if(['submit_task_command','submit_verification'].includes(name)){if(!validateWriterToolArgs(name,args,principal.allowed_roles))throw new Error('INVALID_SCHEMA');return this.roleInterface.submitRoleCommand({principal,acting_role:args.acting_role,command:args.command});}throw new Error('METHOD_NOT_FOUND');}
  async handleMcp(request,response,url,readJson){const actor_id=RESOURCE_ACTORS[url.pathname];if(!actor_id)return false;const resource=this.resource(url.pathname);if(!this.#originAllowed(request))return mcpJson(response,403,{error:'origin_rejected'}),true;if(request.method==='GET'||request.method==='DELETE')return response.writeHead(405,{'allow':'POST','cache-control':'no-store'}).end(),true;if(request.method!=='POST')return mcpJson(response,405,{error:'method_not_allowed'}),true;const principal=await this.authenticate(request,resource);if(!principal||principal.actor_id!==actor_id)return this.#challenge(response,resource),true;let message;try{message=await readJson(request);}catch{return mcpJson(response,400,rpcError(null,-32700,'Parse error')),true;}if(message?.jsonrpc!=='2.0'||typeof message.method!=='string')return mcpJson(response,400,rpcError(message?.id,-32600,'Invalid Request')),true;const protocol=request.headers['mcp-protocol-version']??'2025-03-26';if(message.method!=='initialize'&&!['2025-06-18','2025-03-26'].includes(protocol))return mcpJson(response,400,rpcError(message.id,-32600,'Unsupported MCP protocol version')),true;if(!Object.hasOwn(message,'id'))return response.writeHead(202,{'cache-control':'no-store'}).end(),true;if(message.method==='initialize'){const requested=message.params?.protocolVersion;const protocolVersion=['2025-06-18','2025-03-26'].includes(requested)?requested:MCP_PROTOCOL_VERSION;return mcpJson(response,200,rpcResult(message.id,{protocolVersion,capabilities:{tools:{}},serverInfo:{name:'cf2-production-role-gateway',version:'1.0.0'},instructions:'Actor and roles are bound server-side. Never send actor_id.'})),true;}if(message.method==='ping')return mcpJson(response,200,rpcResult(message.id,{})),true;if(message.method==='tools/list')return mcpJson(response,200,rpcResult(message.id,{tools:mcpToolsFor(principal,{orchestration:Boolean(this.orchestration)})})),true;if(message.method==='tools/call'){const name=message.params?.name,args=message.params?.arguments??{};try{return mcpJson(response,200,rpcResult(message.id,toolResult(await this.#callTool(principal,name,args)))),true;}catch(error){const code=['ROLE_FORBIDDEN','ACTOR_MISMATCH','INVALID_SCHEMA','CUTOVER_DISABLED','WRITER_NOT_AUTHORIZED','CANON_NOT_VERIFIED','THREAD_UNKNOWN','THREAD_TERMINAL','THREAD_ALREADY_EXISTS','THREAD_NOT_COMPLETE','INVALID_STATE','IDEMPOTENCY_CONFLICT','INVALID_DECISION_REASON','SECTION_AMBIGUOUS_OR_UNKNOWN'].includes(error.message)?error.message:'FAIL_CLOSED';return mcpJson(response,200,rpcResult(message.id,toolFailure(code))),true;}}return mcpJson(response,200,rpcError(message.id,-32601,'Method not found')),true;}
  async handlePublic(request,response,url,readJson,readForm){if(request.method==='GET'&&url.pathname.startsWith('/.well-known/oauth-protected-resource')){const suffix=url.pathname.slice('/.well-known/oauth-protected-resource'.length),metadata=this.protectedMetadata(`${this.baseUrl}${suffix}`);return mcpJson(response,metadata?200:404,metadata??{error:'not_found'}),true;}if(request.method==='GET'&&url.pathname==='/.well-known/oauth-authorization-server')return mcpJson(response,200,this.authorizationMetadata()),true;if(request.method==='POST'&&url.pathname==='/oauth/mcp/register'){try{return mcpJson(response,201,await this.register(await readJson(request),request)),true;}catch(error){return mcpJson(response,error.message==='REGISTRATION_RATE_LIMITED'?429:400,{error:'invalid_client_metadata',error_description:error.message}),true;}}if(request.method==='POST'&&url.pathname==='/oauth/mcp/token'){try{return mcpJson(response,200,await this.token(await readForm(request))),true;}catch(error){return mcpJson(response,400,{error:'invalid_grant',error_description:error.message}),true;}}if(request.method==='POST'&&url.pathname==='/oauth/mcp/revoke'){try{await this.revoke(await readForm(request));return response.writeHead(200,{'cache-control':'no-store'}).end(),true;}catch{return mcpJson(response,400,{error:'invalid_request'}),true;}}return false;}
}
